/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BillingCycleProcess model module.
 * @module model/BillingCycleProcess
 * @version 1.0.9
 */
class BillingCycleProcess {
    /**
     * Constructs a new <code>BillingCycleProcess</code>.
     * @alias module:model/BillingCycleProcess
     * @param nextBilledOn {String} 
     */
    constructor(nextBilledOn) { 
        
        BillingCycleProcess.initialize(this, nextBilledOn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nextBilledOn) { 
        obj['nextBilledOn'] = nextBilledOn;
    }

    /**
     * Constructs a <code>BillingCycleProcess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BillingCycleProcess} obj Optional instance to populate.
     * @return {module:model/BillingCycleProcess} The populated <code>BillingCycleProcess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingCycleProcess();

            if (data.hasOwnProperty('nextBilledOn')) {
                obj['nextBilledOn'] = ApiClient.convertToType(data['nextBilledOn'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} nextBilledOn
 */
BillingCycleProcess.prototype['nextBilledOn'] = undefined;






export default BillingCycleProcess;

