/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CostSummary from './CostSummary';

/**
 * The BillingCostsReport model module.
 * @module model/BillingCostsReport
 * @version 1.0.9
 */
class BillingCostsReport {
    /**
     * Constructs a new <code>BillingCostsReport</code>.
     * @alias module:model/BillingCostsReport
     */
    constructor() { 
        
        BillingCostsReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BillingCostsReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BillingCostsReport} obj Optional instance to populate.
     * @return {module:model/BillingCostsReport} The populated <code>BillingCostsReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingCostsReport();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], [CostSummary]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} tenantId
 */
BillingCostsReport.prototype['tenantId'] = undefined;

/**
 * @member {Array.<module:model/CostSummary>} details
 */
BillingCostsReport.prototype['details'] = undefined;






export default BillingCostsReport;

