/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BillingCycle from './BillingCycle';
import BillingCyclesPageAllOf from './BillingCyclesPageAllOf';
import PageHeader from './PageHeader';

/**
 * The BillingCyclesPage model module.
 * @module model/BillingCyclesPage
 * @version 1.0.9
 */
class BillingCyclesPage {
    /**
     * Constructs a new <code>BillingCyclesPage</code>.
     * @alias module:model/BillingCyclesPage
     * @implements module:model/PageHeader
     * @implements module:model/BillingCyclesPageAllOf
     */
    constructor() { 
        PageHeader.initialize(this);BillingCyclesPageAllOf.initialize(this);
        BillingCyclesPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BillingCyclesPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BillingCyclesPage} obj Optional instance to populate.
     * @return {module:model/BillingCyclesPage} The populated <code>BillingCyclesPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingCyclesPage();
            PageHeader.constructFromObject(data, obj);
            BillingCyclesPageAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('totalItems')) {
                obj['totalItems'] = ApiClient.convertToType(data['totalItems'], 'Number');
            }
            if (data.hasOwnProperty('hasNext')) {
                obj['hasNext'] = ApiClient.convertToType(data['hasNext'], 'Boolean');
            }
            if (data.hasOwnProperty('hasPrevious')) {
                obj['hasPrevious'] = ApiClient.convertToType(data['hasPrevious'], 'Boolean');
            }
            if (data.hasOwnProperty('sortBy')) {
                obj['sortBy'] = ApiClient.convertToType(data['sortBy'], 'String');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'String');
            }
            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], [BillingCycle]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} page
 */
BillingCyclesPage.prototype['page'] = undefined;

/**
 * @member {Number} pageSize
 */
BillingCyclesPage.prototype['pageSize'] = undefined;

/**
 * @member {Number} totalItems
 */
BillingCyclesPage.prototype['totalItems'] = undefined;

/**
 * @member {Boolean} hasNext
 */
BillingCyclesPage.prototype['hasNext'] = undefined;

/**
 * @member {Boolean} hasPrevious
 */
BillingCyclesPage.prototype['hasPrevious'] = undefined;

/**
 * @member {String} sortBy
 */
BillingCyclesPage.prototype['sortBy'] = undefined;

/**
 * @member {module:model/BillingCyclesPage.SortOrderEnum} sortOrder
 */
BillingCyclesPage.prototype['sortOrder'] = undefined;

/**
 * @member {Array.<module:model/BillingCycle>} contents
 */
BillingCyclesPage.prototype['contents'] = undefined;


// Implement PageHeader interface:
/**
 * @member {Number} page
 */
PageHeader.prototype['page'] = undefined;
/**
 * @member {Number} pageSize
 */
PageHeader.prototype['pageSize'] = undefined;
/**
 * @member {Number} totalItems
 */
PageHeader.prototype['totalItems'] = undefined;
/**
 * @member {Boolean} hasNext
 */
PageHeader.prototype['hasNext'] = undefined;
/**
 * @member {Boolean} hasPrevious
 */
PageHeader.prototype['hasPrevious'] = undefined;
/**
 * @member {String} sortBy
 */
PageHeader.prototype['sortBy'] = undefined;
/**
 * @member {module:model/PageHeader.SortOrderEnum} sortOrder
 */
PageHeader.prototype['sortOrder'] = undefined;
// Implement BillingCyclesPageAllOf interface:
/**
 * @member {Array.<module:model/BillingCycle>} contents
 */
BillingCyclesPageAllOf.prototype['contents'] = undefined;



/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
BillingCyclesPage['SortOrderEnum'] = {

    /**
     * value: "asc"
     * @const
     */
    "asc": "asc",

    /**
     * value: "desc"
     * @const
     */
    "desc": "desc",

    /**
     * value: "null"
     * @const
     */
    "null": "null"
};



export default BillingCyclesPage;

