/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangeRequestAllOf model module.
 * @module model/ChangeRequestAllOf
 * @version 1.0.9
 */
class ChangeRequestAllOf {
    /**
     * Constructs a new <code>ChangeRequestAllOf</code>.
     * @alias module:model/ChangeRequestAllOf
     */
    constructor() { 
        
        ChangeRequestAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangeRequestAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeRequestAllOf} obj Optional instance to populate.
     * @return {module:model/ChangeRequestAllOf} The populated <code>ChangeRequestAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeRequestAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ChangeRequestAllOf.prototype['id'] = undefined;

/**
 * @member {String} externalId
 */
ChangeRequestAllOf.prototype['externalId'] = undefined;






export default ChangeRequestAllOf;

