/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeviceAllOf model module.
 * @module model/DeviceAllOf
 * @version 1.0.2
 */
class DeviceAllOf {
    /**
     * Constructs a new <code>DeviceAllOf</code>.
     * @alias module:model/DeviceAllOf
     */
    constructor() { 
        
        DeviceAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeviceAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceAllOf} obj Optional instance to populate.
     * @return {module:model/DeviceAllOf} The populated <code>DeviceAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('providerId')) {
                obj['providerId'] = ApiClient.convertToType(data['providerId'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DeviceAllOf.prototype['id'] = undefined;

/**
 * @member {String} userId
 */
DeviceAllOf.prototype['userId'] = undefined;

/**
 * @member {String} providerId
 */
DeviceAllOf.prototype['providerId'] = undefined;

/**
 * @member {Date} createdOn
 */
DeviceAllOf.prototype['createdOn'] = undefined;

/**
 * @member {Date} modifiedOn
 */
DeviceAllOf.prototype['modifiedOn'] = undefined;






export default DeviceAllOf;

