/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Device from './Device';

/**
 * The DevicesPageAllOf model module.
 * @module model/DevicesPageAllOf
 * @version 1.0.1
 */
class DevicesPageAllOf {
    /**
     * Constructs a new <code>DevicesPageAllOf</code>.
     * @alias module:model/DevicesPageAllOf
     */
    constructor() { 
        
        DevicesPageAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DevicesPageAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DevicesPageAllOf} obj Optional instance to populate.
     * @return {module:model/DevicesPageAllOf} The populated <code>DevicesPageAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DevicesPageAllOf();

            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], [Device]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Device>} contents
 */
DevicesPageAllOf.prototype['contents'] = undefined;






export default DevicesPageAllOf;

