/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: somecontact@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NameValue from './NameValue';

/**
 * The DeviceTemplateUpdateDetails model module.
 * @module model/DeviceTemplateUpdateDetails
 * @version 3.10.0
 */
class DeviceTemplateUpdateDetails {
    /**
     * Constructs a new <code>DeviceTemplateUpdateDetails</code>.
     * @alias module:model/DeviceTemplateUpdateDetails
     */
    constructor() { 
        
        DeviceTemplateUpdateDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeviceTemplateUpdateDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceTemplateUpdateDetails} obj Optional instance to populate.
     * @return {module:model/DeviceTemplateUpdateDetails} The populated <code>DeviceTemplateUpdateDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceTemplateUpdateDetails();

            if (data.hasOwnProperty('templateHistoryId')) {
                obj['templateHistoryId'] = ApiClient.convertToType(data['templateHistoryId'], 'String');
            }
            if (data.hasOwnProperty('templateParams')) {
                obj['templateParams'] = ApiClient.convertToType(data['templateParams'], [NameValue]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} templateHistoryId
 */
DeviceTemplateUpdateDetails.prototype['templateHistoryId'] = undefined;

/**
 * @member {Array.<module:model/NameValue>} templateParams
 */
DeviceTemplateUpdateDetails.prototype['templateParams'] = undefined;






export default DeviceTemplateUpdateDetails;

