/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GenericEventSeverity.
* @enum {}
* @readonly
*/
export default class GenericEventSeverity {
    
        /**
         * value: "CRITICAL"
         * @const
         */
        "CRITICAL" = "CRITICAL";

    
        /**
         * value: "POOR"
         * @const
         */
        "POOR" = "POOR";

    
        /**
         * value: "FAIR"
         * @const
         */
        "FAIR" = "FAIR";

    
        /**
         * value: "GOOD"
         * @const
         */
        "GOOD" = "GOOD";

    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    

    /**
    * Returns a <code>GenericEventSeverity</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/GenericEventSeverity} The enum <code>GenericEventSeverity</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

