/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenericEventSecurity model module.
 * @module model/GenericEventSecurity
 * @version 1.0.9
 */
class GenericEventSecurity {
    /**
     * Constructs a new <code>GenericEventSecurity</code>.
     * @alias module:model/GenericEventSecurity
     */
    constructor() { 
        
        GenericEventSecurity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenericEventSecurity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenericEventSecurity} obj Optional instance to populate.
     * @return {module:model/GenericEventSecurity} The populated <code>GenericEventSecurity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenericEventSecurity();

            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('tenantName')) {
                obj['tenantName'] = ApiClient.convertToType(data['tenantName'], 'String');
            }
            if (data.hasOwnProperty('providerId')) {
                obj['providerId'] = ApiClient.convertToType(data['providerId'], 'String');
            }
            if (data.hasOwnProperty('originalUsername')) {
                obj['originalUsername'] = ApiClient.convertToType(data['originalUsername'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} clientId
 */
GenericEventSecurity.prototype['clientId'] = undefined;

/**
 * @member {String} userId
 */
GenericEventSecurity.prototype['userId'] = undefined;

/**
 * @member {String} username
 */
GenericEventSecurity.prototype['username'] = undefined;

/**
 * @member {String} tenantId
 */
GenericEventSecurity.prototype['tenantId'] = undefined;

/**
 * @member {String} tenantName
 */
GenericEventSecurity.prototype['tenantName'] = undefined;

/**
 * @member {String} providerId
 */
GenericEventSecurity.prototype['providerId'] = undefined;

/**
 * @member {String} originalUsername
 */
GenericEventSecurity.prototype['originalUsername'] = undefined;






export default GenericEventSecurity;

