/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GenericEventAllOf from './GenericEventAllOf';
import GenericEventCreate from './GenericEventCreate';
import GenericEventSecurity from './GenericEventSecurity';
import GenericEventSeverity from './GenericEventSeverity';
import GenericEventTrace from './GenericEventTrace';

/**
 * The GenericEvent model module.
 * @module model/GenericEvent
 * @version 1.0.5
 */
class GenericEvent {
    /**
     * Constructs a new <code>GenericEvent</code>.
     * @alias module:model/GenericEvent
     * @implements module:model/GenericEventAllOf
     * @implements module:model/GenericEventCreate
     */
    constructor() { 
        GenericEventAllOf.initialize(this);GenericEventCreate.initialize(this);
        GenericEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenericEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenericEvent} obj Optional instance to populate.
     * @return {module:model/GenericEvent} The populated <code>GenericEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenericEvent();
            GenericEventAllOf.constructFromObject(data, obj);
            GenericEventCreate.constructFromObject(data, obj);

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = GenericEventSeverity.constructFromObject(data['severity']);
            }
            if (data.hasOwnProperty('subtype')) {
                obj['subtype'] = ApiClient.convertToType(data['subtype'], 'String');
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = ApiClient.convertToType(data['service'], 'String');
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ApiClient.convertToType(data['keywords'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], {'String': 'String'});
            }
            if (data.hasOwnProperty('trace')) {
                obj['trace'] = GenericEventTrace.constructFromObject(data['trace']);
            }
            if (data.hasOwnProperty('security')) {
                obj['security'] = GenericEventSecurity.constructFromObject(data['security']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
GenericEvent.prototype['type'] = undefined;

/**
 * @member {Date} time
 */
GenericEvent.prototype['time'] = undefined;

/**
 * @member {module:model/GenericEventSeverity} severity
 */
GenericEvent.prototype['severity'] = undefined;

/**
 * @member {String} subtype
 */
GenericEvent.prototype['subtype'] = undefined;

/**
 * Service that generated the event
 * @member {String} service
 */
GenericEvent.prototype['service'] = undefined;

/**
 * Space separated list of keywords to be used for search
 * @member {String} keywords
 */
GenericEvent.prototype['keywords'] = undefined;

/**
 * @member {Object.<String, String>} details
 */
GenericEvent.prototype['details'] = undefined;

/**
 * @member {module:model/GenericEventTrace} trace
 */
GenericEvent.prototype['trace'] = undefined;

/**
 * @member {module:model/GenericEventSecurity} security
 */
GenericEvent.prototype['security'] = undefined;

/**
 * @member {String} description
 */
GenericEvent.prototype['description'] = undefined;


// Implement GenericEventAllOf interface:
/**
 * @member {String} type
 */
GenericEventAllOf.prototype['type'] = undefined;
/**
 * @member {Date} time
 */
GenericEventAllOf.prototype['time'] = undefined;
// Implement GenericEventCreate interface:
/**
 * @member {module:model/GenericEventSeverity} severity
 */
GenericEventCreate.prototype['severity'] = undefined;
/**
 * @member {String} subtype
 */
GenericEventCreate.prototype['subtype'] = undefined;
/**
 * Service that generated the event
 * @member {String} service
 */
GenericEventCreate.prototype['service'] = undefined;
/**
 * Space separated list of keywords to be used for search
 * @member {String} keywords
 */
GenericEventCreate.prototype['keywords'] = undefined;
/**
 * @member {Object.<String, String>} details
 */
GenericEventCreate.prototype['details'] = undefined;
/**
 * @member {module:model/GenericEventTrace} trace
 */
GenericEventCreate.prototype['trace'] = undefined;
/**
 * @member {module:model/GenericEventSecurity} security
 */
GenericEventCreate.prototype['security'] = undefined;
/**
 * @member {String} description
 */
GenericEventCreate.prototype['description'] = undefined;




export default GenericEvent;

