/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncidentAllOf from './IncidentAllOf';
import IncidentUpdate from './IncidentUpdate';

/**
 * The Incident model module.
 * @module model/Incident
 * @version 1.0.10
 */
class Incident {
    /**
     * Constructs a new <code>Incident</code>.
     * @alias module:model/Incident
     * @implements module:model/IncidentAllOf
     * @implements module:model/IncidentUpdate
     * @param id {String} 
     * @param externalId {String} 
     * @param description {String} 
     */
    constructor(id, externalId, description) { 
        IncidentAllOf.initialize(this, id, externalId);IncidentUpdate.initialize(this, description);
        Incident.initialize(this, id, externalId, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, externalId, description) { 
        obj['id'] = id;
        obj['externalId'] = externalId;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>Incident</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Incident} obj Optional instance to populate.
     * @return {module:model/Incident} The populated <code>Incident</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Incident();
            IncidentAllOf.constructFromObject(data, obj);
            IncidentUpdate.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': Object});
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], ['String']);
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('modifiedBy')) {
                obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'Date');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('impact')) {
                obj['impact'] = ApiClient.convertToType(data['impact'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('subcategory')) {
                obj['subcategory'] = ApiClient.convertToType(data['subcategory'], 'String');
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = ApiClient.convertToType(data['tenant'], 'String');
            }
            if (data.hasOwnProperty('urgency')) {
                obj['urgency'] = ApiClient.convertToType(data['urgency'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Incident.prototype['id'] = undefined;

/**
 * @member {String} externalId
 */
Incident.prototype['externalId'] = undefined;

/**
 * @member {Object.<String, Object>} attributes
 */
Incident.prototype['attributes'] = undefined;

/**
 * @member {Array.<String>} notes
 */
Incident.prototype['notes'] = undefined;

/**
 * @member {String} createdBy
 */
Incident.prototype['createdBy'] = undefined;

/**
 * @member {Date} createdOn
 */
Incident.prototype['createdOn'] = undefined;

/**
 * @member {String} modifiedBy
 */
Incident.prototype['modifiedBy'] = undefined;

/**
 * @member {Date} modifiedOn
 */
Incident.prototype['modifiedOn'] = undefined;

/**
 * inquiry|software|hardware|network|database
 * @member {String} category
 * @default 'inquiry'
 */
Incident.prototype['category'] = 'inquiry';

/**
 * @member {String} description
 */
Incident.prototype['description'] = undefined;

/**
 * @member {module:model/Incident.ImpactEnum} impact
 * @default 'Low'
 */
Incident.prototype['impact'] = 'Low';

/**
 * @member {module:model/Incident.PriorityEnum} priority
 * @default 'Planning'
 */
Incident.prototype['priority'] = 'Planning';

/**
 * @member {module:model/Incident.SeverityEnum} severity
 * @default 'Low'
 */
Incident.prototype['severity'] = 'Low';

/**
 * @member {module:model/Incident.StateEnum} state
 * @default 'New'
 */
Incident.prototype['state'] = 'New';

/**
 * @member {String} subcategory
 */
Incident.prototype['subcategory'] = undefined;

/**
 * @member {String} tenant
 */
Incident.prototype['tenant'] = undefined;

/**
 * @member {module:model/Incident.UrgencyEnum} urgency
 * @default 'Low'
 */
Incident.prototype['urgency'] = 'Low';


// Implement IncidentAllOf interface:
/**
 * @member {String} id
 */
IncidentAllOf.prototype['id'] = undefined;
/**
 * @member {String} externalId
 */
IncidentAllOf.prototype['externalId'] = undefined;
/**
 * @member {Object.<String, Object>} attributes
 */
IncidentAllOf.prototype['attributes'] = undefined;
/**
 * @member {Array.<String>} notes
 */
IncidentAllOf.prototype['notes'] = undefined;
/**
 * @member {String} createdBy
 */
IncidentAllOf.prototype['createdBy'] = undefined;
/**
 * @member {Date} createdOn
 */
IncidentAllOf.prototype['createdOn'] = undefined;
/**
 * @member {String} modifiedBy
 */
IncidentAllOf.prototype['modifiedBy'] = undefined;
/**
 * @member {Date} modifiedOn
 */
IncidentAllOf.prototype['modifiedOn'] = undefined;
// Implement IncidentUpdate interface:
/**
 * @member {Object.<String, Object>} attributes
 */
IncidentUpdate.prototype['attributes'] = undefined;
/**
 * inquiry|software|hardware|network|database
 * @member {String} category
 * @default 'inquiry'
 */
IncidentUpdate.prototype['category'] = 'inquiry';
/**
 * @member {String} description
 */
IncidentUpdate.prototype['description'] = undefined;
/**
 * @member {module:model/IncidentUpdate.ImpactEnum} impact
 * @default 'Low'
 */
IncidentUpdate.prototype['impact'] = 'Low';
/**
 * @member {module:model/IncidentUpdate.PriorityEnum} priority
 * @default 'Planning'
 */
IncidentUpdate.prototype['priority'] = 'Planning';
/**
 * @member {module:model/IncidentUpdate.SeverityEnum} severity
 * @default 'Low'
 */
IncidentUpdate.prototype['severity'] = 'Low';
/**
 * @member {module:model/IncidentUpdate.StateEnum} state
 * @default 'New'
 */
IncidentUpdate.prototype['state'] = 'New';
/**
 * @member {String} subcategory
 */
IncidentUpdate.prototype['subcategory'] = undefined;
/**
 * @member {String} tenant
 */
IncidentUpdate.prototype['tenant'] = undefined;
/**
 * @member {module:model/IncidentUpdate.UrgencyEnum} urgency
 * @default 'Low'
 */
IncidentUpdate.prototype['urgency'] = 'Low';



/**
 * Allowed values for the <code>impact</code> property.
 * @enum {String}
 * @readonly
 */
Incident['ImpactEnum'] = {

    /**
     * value: "High"
     * @const
     */
    "High": "High",

    /**
     * value: "Medium"
     * @const
     */
    "Medium": "Medium",

    /**
     * value: "Low"
     * @const
     */
    "Low": "Low"
};


/**
 * Allowed values for the <code>priority</code> property.
 * @enum {String}
 * @readonly
 */
Incident['PriorityEnum'] = {

    /**
     * value: "Critical"
     * @const
     */
    "Critical": "Critical",

    /**
     * value: "Low"
     * @const
     */
    "Low": "Low",

    /**
     * value: "High"
     * @const
     */
    "High": "High",

    /**
     * value: "Moderate"
     * @const
     */
    "Moderate": "Moderate",

    /**
     * value: "Planning"
     * @const
     */
    "Planning": "Planning"
};


/**
 * Allowed values for the <code>severity</code> property.
 * @enum {String}
 * @readonly
 */
Incident['SeverityEnum'] = {

    /**
     * value: "High"
     * @const
     */
    "High": "High",

    /**
     * value: "Medium"
     * @const
     */
    "Medium": "Medium",

    /**
     * value: "Low"
     * @const
     */
    "Low": "Low"
};


/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
Incident['StateEnum'] = {

    /**
     * value: "New"
     * @const
     */
    "New": "New",

    /**
     * value: "InProgress"
     * @const
     */
    "InProgress": "InProgress",

    /**
     * value: "OnHold"
     * @const
     */
    "OnHold": "OnHold",

    /**
     * value: "Resolved"
     * @const
     */
    "Resolved": "Resolved",

    /**
     * value: "Close"
     * @const
     */
    "Close": "Close",

    /**
     * value: "Canceled"
     * @const
     */
    "Canceled": "Canceled"
};


/**
 * Allowed values for the <code>urgency</code> property.
 * @enum {String}
 * @readonly
 */
Incident['UrgencyEnum'] = {

    /**
     * value: "High"
     * @const
     */
    "High": "High",

    /**
     * value: "Medium"
     * @const
     */
    "Medium": "Medium",

    /**
     * value: "Low"
     * @const
     */
    "Low": "Low"
};



export default Incident;

