/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NameValue from './NameValue';
import OfferUpdate from './OfferUpdate';

/**
 * The OfferCreate model module.
 * @module model/OfferCreate
 * @version 1.0.1
 */
class OfferCreate {
    /**
     * Constructs a new <code>OfferCreate</code>.
     * @alias module:model/OfferCreate
     * @implements module:model/OfferUpdate
     * @param name {String} 
     * @param label {String} 
     * @param description {String} 
     * @param productId {String} 
     * @param version {Number} 
     * @param displayOrder {Number} 
     * @param image {String} 
     * @param supportedProperties {Array.<String>} 
     * @param supportedOptions {Array.<module:model/NameValue>} 
     */
    constructor(name, label, description, productId, version, displayOrder, image, supportedProperties, supportedOptions) { 
        OfferUpdate.initialize(this, name, label, description, productId, version, displayOrder, image, supportedProperties, supportedOptions);
        OfferCreate.initialize(this, name, label, description, productId, version, displayOrder, image, supportedProperties, supportedOptions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, label, description, productId, version, displayOrder, image, supportedProperties, supportedOptions) { 
        obj['name'] = name;
        obj['label'] = label;
        obj['description'] = description;
        obj['productId'] = productId;
        obj['version'] = version;
        obj['displayOrder'] = displayOrder;
        obj['image'] = image;
        obj['supportedProperties'] = supportedProperties;
        obj['supportedOptions'] = supportedOptions;
    }

    /**
     * Constructs a <code>OfferCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OfferCreate} obj Optional instance to populate.
     * @return {module:model/OfferCreate} The populated <code>OfferCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OfferCreate();
            OfferUpdate.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('displayOrder')) {
                obj['displayOrder'] = ApiClient.convertToType(data['displayOrder'], 'Number');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('supportedProperties')) {
                obj['supportedProperties'] = ApiClient.convertToType(data['supportedProperties'], ['String']);
            }
            if (data.hasOwnProperty('supportedOptions')) {
                obj['supportedOptions'] = ApiClient.convertToType(data['supportedOptions'], [NameValue]);
            }
            if (data.hasOwnProperty('approvals')) {
                obj['approvals'] = ApiClient.convertToType(data['approvals'], {'String': ['String']});
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
OfferCreate.prototype['name'] = undefined;

/**
 * @member {String} label
 */
OfferCreate.prototype['label'] = undefined;

/**
 * @member {String} description
 */
OfferCreate.prototype['description'] = undefined;

/**
 * @member {String} productId
 */
OfferCreate.prototype['productId'] = undefined;

/**
 * @member {Number} version
 */
OfferCreate.prototype['version'] = undefined;

/**
 * @member {Number} displayOrder
 */
OfferCreate.prototype['displayOrder'] = undefined;

/**
 * @member {String} image
 */
OfferCreate.prototype['image'] = undefined;

/**
 * @member {String} price
 */
OfferCreate.prototype['price'] = undefined;

/**
 * @member {String} type
 */
OfferCreate.prototype['type'] = undefined;

/**
 * @member {Array.<String>} supportedProperties
 */
OfferCreate.prototype['supportedProperties'] = undefined;

/**
 * @member {Array.<module:model/NameValue>} supportedOptions
 */
OfferCreate.prototype['supportedOptions'] = undefined;

/**
 * @member {Object.<String, Array.<String>>} approvals
 */
OfferCreate.prototype['approvals'] = undefined;


// Implement OfferUpdate interface:
/**
 * @member {String} name
 */
OfferUpdate.prototype['name'] = undefined;
/**
 * @member {String} label
 */
OfferUpdate.prototype['label'] = undefined;
/**
 * @member {String} description
 */
OfferUpdate.prototype['description'] = undefined;
/**
 * @member {String} productId
 */
OfferUpdate.prototype['productId'] = undefined;
/**
 * @member {Number} version
 */
OfferUpdate.prototype['version'] = undefined;
/**
 * @member {Number} displayOrder
 */
OfferUpdate.prototype['displayOrder'] = undefined;
/**
 * @member {String} image
 */
OfferUpdate.prototype['image'] = undefined;
/**
 * @member {String} price
 */
OfferUpdate.prototype['price'] = undefined;
/**
 * @member {String} type
 */
OfferUpdate.prototype['type'] = undefined;
/**
 * @member {Array.<String>} supportedProperties
 */
OfferUpdate.prototype['supportedProperties'] = undefined;
/**
 * @member {Array.<module:model/NameValue>} supportedOptions
 */
OfferUpdate.prototype['supportedOptions'] = undefined;
/**
 * @member {Object.<String, Array.<String>>} approvals
 */
OfferUpdate.prototype['approvals'] = undefined;




export default OfferCreate;

