/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Offer from './Offer';

/**
 * The OffersPageAllOf model module.
 * @module model/OffersPageAllOf
 * @version 1.0.2
 */
class OffersPageAllOf {
    /**
     * Constructs a new <code>OffersPageAllOf</code>.
     * @alias module:model/OffersPageAllOf
     */
    constructor() { 
        
        OffersPageAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OffersPageAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OffersPageAllOf} obj Optional instance to populate.
     * @return {module:model/OffersPageAllOf} The populated <code>OffersPageAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OffersPageAllOf();

            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], [Offer]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Offer>} contents
 */
OffersPageAllOf.prototype['contents'] = undefined;






export default OffersPageAllOf;

