/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceUpdate model module.
 * @module model/ServiceUpdate
 * @version 1.0.9
 */
class ServiceUpdate {
    /**
     * Constructs a new <code>ServiceUpdate</code>.
     * @alias module:model/ServiceUpdate
     */
    constructor() { 
        
        ServiceUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceUpdate} obj Optional instance to populate.
     * @return {module:model/ServiceUpdate} The populated <code>ServiceUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceUpdate();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], {'String': Object});
            }
            if (data.hasOwnProperty('definitionAttributes')) {
                obj['definitionAttributes'] = ApiClient.convertToType(data['definitionAttributes'], {'String': Object});
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} status
 */
ServiceUpdate.prototype['status'] = undefined;

/**
 * @member {Object.<String, Object>} definitionAttributes
 */
ServiceUpdate.prototype['definitionAttributes'] = undefined;

/**
 * @member {Object.<String, Object>} attributes
 */
ServiceUpdate.prototype['attributes'] = undefined;






export default ServiceUpdate;

