/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SiteAddress from './SiteAddress';
import SiteContact from './SiteContact';
import SiteCreateAllOf from './SiteCreateAllOf';
import SiteLocation from './SiteLocation';
import SiteUpdate from './SiteUpdate';

/**
 * The SiteCreate model module.
 * @module model/SiteCreate
 * @version 1.0.2
 */
class SiteCreate {
    /**
     * Constructs a new <code>SiteCreate</code>.
     * @alias module:model/SiteCreate
     * @implements module:model/SiteCreateAllOf
     * @implements module:model/SiteUpdate
     * @param tenantId {String} 
     * @param name {String} 
     */
    constructor(tenantId, name) { 
        SiteCreateAllOf.initialize(this, tenantId);SiteUpdate.initialize(this, name);
        SiteCreate.initialize(this, tenantId, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tenantId, name) { 
        obj['tenantId'] = tenantId;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>SiteCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SiteCreate} obj Optional instance to populate.
     * @return {module:model/SiteCreate} The populated <code>SiteCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SiteCreate();
            SiteCreateAllOf.constructFromObject(data, obj);
            SiteUpdate.constructFromObject(data, obj);

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('deviceIds')) {
                obj['deviceIds'] = ApiClient.convertToType(data['deviceIds'], ['String']);
            }
            if (data.hasOwnProperty('serviceIds')) {
                obj['serviceIds'] = ApiClient.convertToType(data['serviceIds'], ['String']);
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = SiteAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = SiteContact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = SiteLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {String} tenantId
 */
SiteCreate.prototype['tenantId'] = undefined;

/**
 * @member {Array.<String>} deviceIds
 */
SiteCreate.prototype['deviceIds'] = undefined;

/**
 * @member {Array.<String>} serviceIds
 */
SiteCreate.prototype['serviceIds'] = undefined;

/**
 * @member {String} parentId
 */
SiteCreate.prototype['parentId'] = undefined;

/**
 * @member {String} name
 */
SiteCreate.prototype['name'] = undefined;

/**
 * @member {String} description
 */
SiteCreate.prototype['description'] = undefined;

/**
 * @member {String} type
 */
SiteCreate.prototype['type'] = undefined;

/**
 * @member {module:model/SiteAddress} address
 */
SiteCreate.prototype['address'] = undefined;

/**
 * @member {module:model/SiteContact} contact
 */
SiteCreate.prototype['contact'] = undefined;

/**
 * @member {module:model/SiteLocation} location
 */
SiteCreate.prototype['location'] = undefined;

/**
 * @member {String} image
 */
SiteCreate.prototype['image'] = undefined;

/**
 * @member {Object.<String, String>} attributes
 */
SiteCreate.prototype['attributes'] = undefined;


// Implement SiteCreateAllOf interface:
/**
 * @member {String} tenantId
 */
SiteCreateAllOf.prototype['tenantId'] = undefined;
/**
 * @member {Array.<String>} deviceIds
 */
SiteCreateAllOf.prototype['deviceIds'] = undefined;
/**
 * @member {Array.<String>} serviceIds
 */
SiteCreateAllOf.prototype['serviceIds'] = undefined;
// Implement SiteUpdate interface:
/**
 * @member {String} parentId
 */
SiteUpdate.prototype['parentId'] = undefined;
/**
 * @member {String} name
 */
SiteUpdate.prototype['name'] = undefined;
/**
 * @member {String} description
 */
SiteUpdate.prototype['description'] = undefined;
/**
 * @member {String} type
 */
SiteUpdate.prototype['type'] = undefined;
/**
 * @member {module:model/SiteAddress} address
 */
SiteUpdate.prototype['address'] = undefined;
/**
 * @member {module:model/SiteContact} contact
 */
SiteUpdate.prototype['contact'] = undefined;
/**
 * @member {module:model/SiteLocation} location
 */
SiteUpdate.prototype['location'] = undefined;
/**
 * @member {String} image
 */
SiteUpdate.prototype['image'] = undefined;
/**
 * @member {Object.<String, String>} attributes
 */
SiteUpdate.prototype['attributes'] = undefined;




export default SiteCreate;

