/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SiteCreateAllOf model module.
 * @module model/SiteCreateAllOf
 * @version 1.0.8
 */
class SiteCreateAllOf {
    /**
     * Constructs a new <code>SiteCreateAllOf</code>.
     * @alias module:model/SiteCreateAllOf
     * @param tenantId {String} 
     */
    constructor(tenantId) { 
        
        SiteCreateAllOf.initialize(this, tenantId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tenantId) { 
        obj['tenantId'] = tenantId;
    }

    /**
     * Constructs a <code>SiteCreateAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SiteCreateAllOf} obj Optional instance to populate.
     * @return {module:model/SiteCreateAllOf} The populated <code>SiteCreateAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SiteCreateAllOf();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('deviceIds')) {
                obj['deviceIds'] = ApiClient.convertToType(data['deviceIds'], ['String']);
            }
            if (data.hasOwnProperty('serviceIds')) {
                obj['serviceIds'] = ApiClient.convertToType(data['serviceIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} tenantId
 */
SiteCreateAllOf.prototype['tenantId'] = undefined;

/**
 * @member {Array.<String>} deviceIds
 */
SiteCreateAllOf.prototype['deviceIds'] = undefined;

/**
 * @member {Array.<String>} serviceIds
 */
SiteCreateAllOf.prototype['serviceIds'] = undefined;






export default SiteCreateAllOf;

