/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SmartAccountType from './SmartAccountType';
import SmartAccountUserRole from './SmartAccountUserRole';

/**
 * The SmartAccountUser model module.
 * @module model/SmartAccountUser
 * @version 1.0.8
 */
class SmartAccountUser {
    /**
     * Constructs a new <code>SmartAccountUser</code>.
     * @alias module:model/SmartAccountUser
     */
    constructor() { 
        
        SmartAccountUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SmartAccountUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SmartAccountUser} obj Optional instance to populate.
     * @return {module:model/SmartAccountUser} The populated <code>SmartAccountUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmartAccountUser();

            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'Number');
            }
            if (data.hasOwnProperty('accountName')) {
                obj['accountName'] = ApiClient.convertToType(data['accountName'], 'String');
            }
            if (data.hasOwnProperty('accountDomain')) {
                obj['accountDomain'] = ApiClient.convertToType(data['accountDomain'], 'String');
            }
            if (data.hasOwnProperty('accountType')) {
                obj['accountType'] = SmartAccountType.constructFromObject(data['accountType']);
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [SmartAccountUserRole]);
            }
        }
        return obj;
    }


}

/**
 * Smart Account identifier
 * @member {Number} accountId
 */
SmartAccountUser.prototype['accountId'] = undefined;

/**
 * Smart Account Name
 * @member {String} accountName
 */
SmartAccountUser.prototype['accountName'] = undefined;

/**
 * Smart Accont Domain
 * @member {String} accountDomain
 */
SmartAccountUser.prototype['accountDomain'] = undefined;

/**
 * @member {module:model/SmartAccountType} accountType
 */
SmartAccountUser.prototype['accountType'] = undefined;

/**
 * @member {Array.<module:model/SmartAccountUserRole>} roles
 */
SmartAccountUser.prototype['roles'] = undefined;






export default SmartAccountUser;

