/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StartWorkflowResponse model module.
 * @module model/StartWorkflowResponse
 * @version 1.0.9
 */
class StartWorkflowResponse {
    /**
     * Constructs a new <code>StartWorkflowResponse</code>.
     * @alias module:model/StartWorkflowResponse
     */
    constructor() { 
        
        StartWorkflowResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StartWorkflowResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StartWorkflowResponse} obj Optional instance to populate.
     * @return {module:model/StartWorkflowResponse} The populated <code>StartWorkflowResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StartWorkflowResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('definition_id')) {
                obj['definition_id'] = ApiClient.convertToType(data['definition_id'], 'String');
            }
            if (data.hasOwnProperty('schema_id')) {
                obj['schema_id'] = ApiClient.convertToType(data['schema_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('base_type')) {
                obj['base_type'] = ApiClient.convertToType(data['base_type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], {'String': Object});
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
StartWorkflowResponse.prototype['id'] = undefined;

/**
 * @member {String} definition_id
 */
StartWorkflowResponse.prototype['definition_id'] = undefined;

/**
 * @member {String} schema_id
 */
StartWorkflowResponse.prototype['schema_id'] = undefined;

/**
 * @member {String} type
 */
StartWorkflowResponse.prototype['type'] = undefined;

/**
 * @member {String} base_type
 */
StartWorkflowResponse.prototype['base_type'] = undefined;

/**
 * @member {Object.<String, Object>} status
 */
StartWorkflowResponse.prototype['status'] = undefined;

/**
 * @member {String} version
 */
StartWorkflowResponse.prototype['version'] = undefined;

/**
 * @member {String} created_by
 */
StartWorkflowResponse.prototype['created_by'] = undefined;

/**
 * @member {String} created_on
 */
StartWorkflowResponse.prototype['created_on'] = undefined;






export default StartWorkflowResponse;

