/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TemplateAssignmentResponseAllOf model module.
 * @module model/TemplateAssignmentResponseAllOf
 * @version 1.0.10
 */
class TemplateAssignmentResponseAllOf {
    /**
     * Constructs a new <code>TemplateAssignmentResponseAllOf</code>.
     * @alias module:model/TemplateAssignmentResponseAllOf
     */
    constructor() { 
        
        TemplateAssignmentResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplateAssignmentResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateAssignmentResponseAllOf} obj Optional instance to populate.
     * @return {module:model/TemplateAssignmentResponseAllOf} The populated <code>TemplateAssignmentResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateAssignmentResponseAllOf();

            if (data.hasOwnProperty('responseStatus')) {
                obj['responseStatus'] = ApiClient.convertToType(data['responseStatus'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TemplateAssignmentResponseAllOf.ResponseStatusEnum} responseStatus
 */
TemplateAssignmentResponseAllOf.prototype['responseStatus'] = undefined;





/**
 * Allowed values for the <code>responseStatus</code> property.
 * @enum {String}
 * @readonly
 */
TemplateAssignmentResponseAllOf['ResponseStatusEnum'] = {

    /**
     * value: "NEW"
     * @const
     */
    "NEW": "NEW",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "CONFLICT"
     * @const
     */
    "CONFLICT": "CONFLICT",

    /**
     * value: "UNASSIGNED"
     * @const
     */
    "UNASSIGNED": "UNASSIGNED",

    /**
     * value: "ERROR"
     * @const
     */
    "ERROR": "ERROR"
};



export default TemplateAssignmentResponseAllOf;

