/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowAction from './WorkflowAction';

/**
 * The WorkflowActionBlock model module.
 * @module model/WorkflowActionBlock
 * @version 1.0.1
 */
class WorkflowActionBlock {
    /**
     * Constructs a new <code>WorkflowActionBlock</code>.
     * @alias module:model/WorkflowActionBlock
     */
    constructor() { 
        
        WorkflowActionBlock.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowActionBlock</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowActionBlock} obj Optional instance to populate.
     * @return {module:model/WorkflowActionBlock} The populated <code>WorkflowActionBlock</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowActionBlock();

            if (data.hasOwnProperty('unique_name')) {
                obj['unique_name'] = ApiClient.convertToType(data['unique_name'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('base_type')) {
                obj['base_type'] = ApiClient.convertToType(data['base_type'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': Object});
            }
            if (data.hasOwnProperty('object_type')) {
                obj['object_type'] = ApiClient.convertToType(data['object_type'], 'String');
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [WorkflowAction]);
            }
            if (data.hasOwnProperty('subworkflow_id')) {
                obj['subworkflow_id'] = ApiClient.convertToType(data['subworkflow_id'], 'String');
            }
            if (data.hasOwnProperty('workflow_id')) {
                obj['workflow_id'] = ApiClient.convertToType(data['workflow_id'], 'String');
            }
            if (data.hasOwnProperty('schema_id')) {
                obj['schema_id'] = ApiClient.convertToType(data['schema_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} unique_name
 */
WorkflowActionBlock.prototype['unique_name'] = undefined;

/**
 * @member {String} name
 */
WorkflowActionBlock.prototype['name'] = undefined;

/**
 * @member {String} title
 */
WorkflowActionBlock.prototype['title'] = undefined;

/**
 * @member {String} type
 */
WorkflowActionBlock.prototype['type'] = undefined;

/**
 * @member {String} version
 */
WorkflowActionBlock.prototype['version'] = undefined;

/**
 * @member {String} base_type
 */
WorkflowActionBlock.prototype['base_type'] = undefined;

/**
 * @member {Object.<String, Object>} properties
 */
WorkflowActionBlock.prototype['properties'] = undefined;

/**
 * @member {String} object_type
 */
WorkflowActionBlock.prototype['object_type'] = undefined;

/**
 * @member {Array.<module:model/WorkflowAction>} actions
 */
WorkflowActionBlock.prototype['actions'] = undefined;

/**
 * @member {String} subworkflow_id
 */
WorkflowActionBlock.prototype['subworkflow_id'] = undefined;

/**
 * @member {String} workflow_id
 */
WorkflowActionBlock.prototype['workflow_id'] = undefined;

/**
 * @member {String} schema_id
 */
WorkflowActionBlock.prototype['schema_id'] = undefined;






export default WorkflowActionBlock;

