/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowActionBlock from './WorkflowActionBlock';

/**
 * The WorkflowAction model module.
 * @module model/WorkflowAction
 * @version 1.0.9
 */
class WorkflowAction {
    /**
     * Constructs a new <code>WorkflowAction</code>.
     * @alias module:model/WorkflowAction
     */
    constructor() { 
        
        WorkflowAction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowAction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowAction} obj Optional instance to populate.
     * @return {module:model/WorkflowAction} The populated <code>WorkflowAction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowAction();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('workflow_id')) {
                obj['workflow_id'] = ApiClient.convertToType(data['workflow_id'], 'String');
            }
            if (data.hasOwnProperty('definition_id')) {
                obj['definition_id'] = ApiClient.convertToType(data['definition_id'], 'String');
            }
            if (data.hasOwnProperty('schema_id')) {
                obj['schema_id'] = ApiClient.convertToType(data['schema_id'], 'String');
            }
            if (data.hasOwnProperty('adapter_id')) {
                obj['adapter_id'] = ApiClient.convertToType(data['adapter_id'], 'String');
            }
            if (data.hasOwnProperty('unique_name')) {
                obj['unique_name'] = ApiClient.convertToType(data['unique_name'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('base_type')) {
                obj['base_type'] = ApiClient.convertToType(data['base_type'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': Object});
            }
            if (data.hasOwnProperty('object_type')) {
                obj['object_type'] = ApiClient.convertToType(data['object_type'], 'String');
            }
            if (data.hasOwnProperty('started_by')) {
                obj['started_by'] = ApiClient.convertToType(data['started_by'], 'String');
            }
            if (data.hasOwnProperty('blocks')) {
                obj['blocks'] = ApiClient.convertToType(data['blocks'], [WorkflowActionBlock]);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], {'String': Object});
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('output')) {
                obj['output'] = ApiClient.convertToType(data['output'], {'String': Object});
            }
            if (data.hasOwnProperty('started_on')) {
                obj['started_on'] = ApiClient.convertToType(data['started_on'], 'String');
            }
            if (data.hasOwnProperty('ended_on')) {
                obj['ended_on'] = ApiClient.convertToType(data['ended_on'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
WorkflowAction.prototype['id'] = undefined;

/**
 * @member {String} workflow_id
 */
WorkflowAction.prototype['workflow_id'] = undefined;

/**
 * @member {String} definition_id
 */
WorkflowAction.prototype['definition_id'] = undefined;

/**
 * @member {String} schema_id
 */
WorkflowAction.prototype['schema_id'] = undefined;

/**
 * @member {String} adapter_id
 */
WorkflowAction.prototype['adapter_id'] = undefined;

/**
 * @member {String} unique_name
 */
WorkflowAction.prototype['unique_name'] = undefined;

/**
 * @member {String} name
 */
WorkflowAction.prototype['name'] = undefined;

/**
 * @member {String} title
 */
WorkflowAction.prototype['title'] = undefined;

/**
 * @member {String} type
 */
WorkflowAction.prototype['type'] = undefined;

/**
 * @member {String} base_type
 */
WorkflowAction.prototype['base_type'] = undefined;

/**
 * @member {Object.<String, Object>} properties
 */
WorkflowAction.prototype['properties'] = undefined;

/**
 * @member {String} object_type
 */
WorkflowAction.prototype['object_type'] = undefined;

/**
 * @member {String} started_by
 */
WorkflowAction.prototype['started_by'] = undefined;

/**
 * @member {Array.<module:model/WorkflowActionBlock>} blocks
 */
WorkflowAction.prototype['blocks'] = undefined;

/**
 * @member {Object.<String, Object>} status
 */
WorkflowAction.prototype['status'] = undefined;

/**
 * @member {String} description
 */
WorkflowAction.prototype['description'] = undefined;

/**
 * @member {Object.<String, Object>} output
 */
WorkflowAction.prototype['output'] = undefined;

/**
 * @member {String} started_on
 */
WorkflowAction.prototype['started_on'] = undefined;

/**
 * @member {String} ended_on
 */
WorkflowAction.prototype['ended_on'] = undefined;






export default WorkflowAction;

