/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowFooter from './WorkflowFooter';
import WorkflowVariableAllOf from './WorkflowVariableAllOf';

/**
 * The WorkflowVariable model module.
 * @module model/WorkflowVariable
 * @version 1.0.9
 */
class WorkflowVariable {
    /**
     * Constructs a new <code>WorkflowVariable</code>.
     * @alias module:model/WorkflowVariable
     * @implements module:model/WorkflowVariableAllOf
     * @implements module:model/WorkflowFooter
     */
    constructor() { 
        WorkflowVariableAllOf.initialize(this);WorkflowFooter.initialize(this);
        WorkflowVariable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowVariable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowVariable} obj Optional instance to populate.
     * @return {module:model/WorkflowVariable} The populated <code>WorkflowVariable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowVariable();
            WorkflowVariableAllOf.constructFromObject(data, obj);
            WorkflowFooter.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('base_type')) {
                obj['base_type'] = ApiClient.convertToType(data['base_type'], 'String');
            }
            if (data.hasOwnProperty('schema_id')) {
                obj['schema_id'] = ApiClient.convertToType(data['schema_id'], 'String');
            }
            if (data.hasOwnProperty('object_type')) {
                obj['object_type'] = ApiClient.convertToType(data['object_type'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': Object});
            }
            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('updated_on')) {
                obj['updated_on'] = ApiClient.convertToType(data['updated_on'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('unique_name')) {
                obj['unique_name'] = ApiClient.convertToType(data['unique_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
WorkflowVariable.prototype['id'] = undefined;

/**
 * @member {String} type
 */
WorkflowVariable.prototype['type'] = undefined;

/**
 * @member {String} base_type
 */
WorkflowVariable.prototype['base_type'] = undefined;

/**
 * @member {String} schema_id
 */
WorkflowVariable.prototype['schema_id'] = undefined;

/**
 * @member {String} object_type
 */
WorkflowVariable.prototype['object_type'] = undefined;

/**
 * @member {Object.<String, Object>} properties
 */
WorkflowVariable.prototype['properties'] = undefined;

/**
 * @member {String} data_type
 */
WorkflowVariable.prototype['data_type'] = undefined;

/**
 * @member {String} scope
 */
WorkflowVariable.prototype['scope'] = undefined;

/**
 * @member {String} created_on
 */
WorkflowVariable.prototype['created_on'] = undefined;

/**
 * @member {String} created_by
 */
WorkflowVariable.prototype['created_by'] = undefined;

/**
 * @member {String} updated_on
 */
WorkflowVariable.prototype['updated_on'] = undefined;

/**
 * @member {String} updated_by
 */
WorkflowVariable.prototype['updated_by'] = undefined;

/**
 * @member {String} owner
 */
WorkflowVariable.prototype['owner'] = undefined;

/**
 * @member {String} unique_name
 */
WorkflowVariable.prototype['unique_name'] = undefined;


// Implement WorkflowVariableAllOf interface:
/**
 * @member {String} id
 */
WorkflowVariableAllOf.prototype['id'] = undefined;
/**
 * @member {String} type
 */
WorkflowVariableAllOf.prototype['type'] = undefined;
/**
 * @member {String} base_type
 */
WorkflowVariableAllOf.prototype['base_type'] = undefined;
/**
 * @member {String} schema_id
 */
WorkflowVariableAllOf.prototype['schema_id'] = undefined;
/**
 * @member {String} object_type
 */
WorkflowVariableAllOf.prototype['object_type'] = undefined;
/**
 * @member {Object.<String, Object>} properties
 */
WorkflowVariableAllOf.prototype['properties'] = undefined;
/**
 * @member {String} data_type
 */
WorkflowVariableAllOf.prototype['data_type'] = undefined;
/**
 * @member {String} scope
 */
WorkflowVariableAllOf.prototype['scope'] = undefined;
// Implement WorkflowFooter interface:
/**
 * @member {String} created_on
 */
WorkflowFooter.prototype['created_on'] = undefined;
/**
 * @member {String} created_by
 */
WorkflowFooter.prototype['created_by'] = undefined;
/**
 * @member {String} updated_on
 */
WorkflowFooter.prototype['updated_on'] = undefined;
/**
 * @member {String} updated_by
 */
WorkflowFooter.prototype['updated_by'] = undefined;
/**
 * @member {String} owner
 */
WorkflowFooter.prototype['owner'] = undefined;
/**
 * @member {String} unique_name
 */
WorkflowFooter.prototype['unique_name'] = undefined;




export default WorkflowVariable;

