/**
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowMapping model module.
 * @module model/WorkflowMapping
 * @version 1.0.2
 */
class WorkflowMapping {
    /**
     * Constructs a new <code>WorkflowMapping</code>.
     * @alias module:model/WorkflowMapping
     */
    constructor() { 
        
        WorkflowMapping.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowMapping</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowMapping} obj Optional instance to populate.
     * @return {module:model/WorkflowMapping} The populated <code>WorkflowMapping</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowMapping();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('tenantIds')) {
                obj['tenantIds'] = ApiClient.convertToType(data['tenantIds'], ['String']);
            }
            if (data.hasOwnProperty('uniqueName')) {
                obj['uniqueName'] = ApiClient.convertToType(data['uniqueName'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('modifiedBy')) {
                obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
WorkflowMapping.prototype['id'] = undefined;

/**
 * @member {Array.<String>} tenantIds
 */
WorkflowMapping.prototype['tenantIds'] = undefined;

/**
 * @member {String} uniqueName
 */
WorkflowMapping.prototype['uniqueName'] = undefined;

/**
 * @member {String} createdBy
 */
WorkflowMapping.prototype['createdBy'] = undefined;

/**
 * @member {String} createdOn
 */
WorkflowMapping.prototype['createdOn'] = undefined;

/**
 * @member {String} modifiedBy
 */
WorkflowMapping.prototype['modifiedBy'] = undefined;

/**
 * @member {String} modifiedOn
 */
WorkflowMapping.prototype['modifiedOn'] = undefined;






export default WorkflowMapping;

