/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JavascriptMsxSdk);
  }
}(this, function(expect, JavascriptMsxSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JavascriptMsxSdk.LicenseSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LicenseSummary', function() {
    it('should create an instance of LicenseSummary', function() {
      // uncomment below and update the code to test LicenseSummary
      //var instane = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be.a(JavascriptMsxSdk.LicenseSummary);
    });

    it('should have the property entitled (base name: "entitled")', function() {
      // uncomment below and update the code to test the property entitled
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

    it('should have the property inuse (base name: "inuse")', function() {
      // uncomment below and update the code to test the property inuse
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

    it('should have the property reserved (base name: "reserved")', function() {
      // uncomment below and update the code to test the property reserved
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

    it('should have the property enforced (base name: "enforced")', function() {
      // uncomment below and update the code to test the property enforced
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

    it('should have the property licenseDetails (base name: "licenseDetails")', function() {
      // uncomment below and update the code to test the property licenseDetails
      //var instance = new JavascriptMsxSdk.LicenseSummary();
      //expect(instance).to.be();
    });

  });

}));
