/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccessToken from './model/AccessToken';
import BillingCostsReport from './model/BillingCostsReport';
import BillingCycle from './model/BillingCycle';
import BillingCycleAllOf from './model/BillingCycleAllOf';
import BillingCycleCreate from './model/BillingCycleCreate';
import BillingCycleProcess from './model/BillingCycleProcess';
import BillingCycleProcessAccepted from './model/BillingCycleProcessAccepted';
import BillingCycleUpdate from './model/BillingCycleUpdate';
import BillingCyclesPage from './model/BillingCyclesPage';
import BillingCyclesPageAllOf from './model/BillingCyclesPageAllOf';
import BillingEvent from './model/BillingEvent';
import BillingEventAllOf from './model/BillingEventAllOf';
import BillingEventCreate from './model/BillingEventCreate';
import BillingEventUpdate from './model/BillingEventUpdate';
import BillingEventsPage from './model/BillingEventsPage';
import BillingEventsPageAllOf from './model/BillingEventsPageAllOf';
import BillingPrice from './model/BillingPrice';
import BillingPriceAllOf from './model/BillingPriceAllOf';
import BillingPriceCreate from './model/BillingPriceCreate';
import BillingPriceUpdate from './model/BillingPriceUpdate';
import BillingPricesPage from './model/BillingPricesPage';
import BillingPricesPageAllOf from './model/BillingPricesPageAllOf';
import CatalogAssignment from './model/CatalogAssignment';
import ChangeRequest from './model/ChangeRequest';
import ChangeRequestAllOf from './model/ChangeRequestAllOf';
import ChangeRequestCreate from './model/ChangeRequestCreate';
import ChangeRequestSummary from './model/ChangeRequestSummary';
import ChangeRequestUpdate from './model/ChangeRequestUpdate';
import ChangeRequestsPage from './model/ChangeRequestsPage';
import ChangeRequestsPageAllOf from './model/ChangeRequestsPageAllOf';
import CostSummary from './model/CostSummary';
import Device from './model/Device';
import DeviceAllOf from './model/DeviceAllOf';
import DeviceConfigUpdate from './model/DeviceConfigUpdate';
import DeviceCreate from './model/DeviceCreate';
import DeviceCreateAllOf from './model/DeviceCreateAllOf';
import DevicePatch from './model/DevicePatch';
import DeviceSummary from './model/DeviceSummary';
import DeviceTemplate from './model/DeviceTemplate';
import DeviceTemplateAccess from './model/DeviceTemplateAccess';
import DeviceTemplateAccessResponse from './model/DeviceTemplateAccessResponse';
import DeviceTemplateAttachRequest from './model/DeviceTemplateAttachRequest';
import DeviceTemplateBatchAttachRequest from './model/DeviceTemplateBatchAttachRequest';
import DeviceTemplateCreate from './model/DeviceTemplateCreate';
import DeviceTemplateDetails from './model/DeviceTemplateDetails';
import DeviceTemplateHistory from './model/DeviceTemplateHistory';
import DeviceTemplateHistorySummary from './model/DeviceTemplateHistorySummary';
import DeviceTemplateUpdateDetails from './model/DeviceTemplateUpdateDetails';
import DeviceTemplateUpdateRequest from './model/DeviceTemplateUpdateRequest';
import DeviceTemplateVersionCreate from './model/DeviceTemplateVersionCreate';
import DeviceUpdate from './model/DeviceUpdate';
import DeviceUpdateAllOf from './model/DeviceUpdateAllOf';
import DevicesPage from './model/DevicesPage';
import DevicesPageAllOf from './model/DevicesPageAllOf';
import Error from './model/Error';
import GenericEvent from './model/GenericEvent';
import GenericEventAllOf from './model/GenericEventAllOf';
import GenericEventCreate from './model/GenericEventCreate';
import GenericEventSecurity from './model/GenericEventSecurity';
import GenericEventSeverity from './model/GenericEventSeverity';
import GenericEventTrace from './model/GenericEventTrace';
import Incident from './model/Incident';
import IncidentAllOf from './model/IncidentAllOf';
import IncidentCancel from './model/IncidentCancel';
import IncidentConfig from './model/IncidentConfig';
import IncidentConfigPatch from './model/IncidentConfigPatch';
import IncidentConfigUpdate from './model/IncidentConfigUpdate';
import IncidentCreate from './model/IncidentCreate';
import IncidentUpdate from './model/IncidentUpdate';
import IncidentsPage from './model/IncidentsPage';
import IncidentsPageAllOf from './model/IncidentsPageAllOf';
import LegacyAbsoluteConfig from './model/LegacyAbsoluteConfig';
import LegacyAddress from './model/LegacyAddress';
import LegacyNsoResponseTypes from './model/LegacyNsoResponseTypes';
import LegacyRelativeConfig from './model/LegacyRelativeConfig';
import LegacyScheduleConfig from './model/LegacyScheduleConfig';
import LegacyServiceOrder from './model/LegacyServiceOrder';
import LegacyServiceOrderDetail from './model/LegacyServiceOrderDetail';
import LegacyServiceOrderResponse from './model/LegacyServiceOrderResponse';
import LegacySite from './model/LegacySite';
import LegacySiteDevice from './model/LegacySiteDevice';
import LegacySiteDeviceOnboard from './model/LegacySiteDeviceOnboard';
import LegacySubscriptionDetail from './model/LegacySubscriptionDetail';
import LicenseDetails from './model/LicenseDetails';
import LicenseSummary from './model/LicenseSummary';
import ManageChangeRequestPending from './model/ManageChangeRequestPending';
import NSOConfigDataXPath from './model/NSOConfigDataXPath';
import NameValue from './model/NameValue';
import Offer from './model/Offer';
import OfferAllOf from './model/OfferAllOf';
import OfferCreate from './model/OfferCreate';
import OfferUpdate from './model/OfferUpdate';
import OffersPage from './model/OffersPage';
import OffersPageAllOf from './model/OffersPageAllOf';
import PageHeader from './model/PageHeader';
import Product from './model/Product';
import ProductAllOf from './model/ProductAllOf';
import ProductCreate from './model/ProductCreate';
import ProductUpdate from './model/ProductUpdate';
import ProductsPage from './model/ProductsPage';
import ProductsPageAllOf from './model/ProductsPageAllOf';
import ResourceHealth from './model/ResourceHealth';
import ResourceStatus from './model/ResourceStatus';
import ResourceType from './model/ResourceType';
import Role from './model/Role';
import Service from './model/Service';
import ServiceAllOf from './model/ServiceAllOf';
import ServiceElement from './model/ServiceElement';
import ServiceElementPrice from './model/ServiceElementPrice';
import ServiceNowConfiguration from './model/ServiceNowConfiguration';
import ServiceNowConfigurationCreate from './model/ServiceNowConfigurationCreate';
import ServiceNowConfigurationRequest from './model/ServiceNowConfigurationRequest';
import ServiceNowConfigurationsPage from './model/ServiceNowConfigurationsPage';
import ServiceNowConfigurationsPageAllOf from './model/ServiceNowConfigurationsPageAllOf';
import ServiceSLMUIConfig from './model/ServiceSLMUIConfig';
import ServiceUIConfig from './model/ServiceUIConfig';
import ServiceUILink from './model/ServiceUILink';
import ServiceUIResource from './model/ServiceUIResource';
import ServiceUpdate from './model/ServiceUpdate';
import ServicesPage from './model/ServicesPage';
import ServicesPageAllOf from './model/ServicesPageAllOf';
import Site from './model/Site';
import SiteAddress from './model/SiteAddress';
import SiteContact from './model/SiteContact';
import SiteCreate from './model/SiteCreate';
import SiteCreateAllOf from './model/SiteCreateAllOf';
import SiteLocation from './model/SiteLocation';
import SiteStatus from './model/SiteStatus';
import SiteUpdate from './model/SiteUpdate';
import SitesPage from './model/SitesPage';
import SitesPageAllOf from './model/SitesPageAllOf';
import SmartAccountConfiguration from './model/SmartAccountConfiguration';
import SmartAccountConfigurationCreate from './model/SmartAccountConfigurationCreate';
import SmartAccountConfigurationUpdate from './model/SmartAccountConfigurationUpdate';
import SmartAccountType from './model/SmartAccountType';
import SmartAccountUser from './model/SmartAccountUser';
import SmartAccountUserRole from './model/SmartAccountUserRole';
import SmartUserAccounts from './model/SmartUserAccounts';
import SmartUserAccountsAllOf from './model/SmartUserAccountsAllOf';
import StartWorkflowResponse from './model/StartWorkflowResponse';
import Template from './model/Template';
import TemplateApplication from './model/TemplateApplication';
import TemplateApplicationAllOf from './model/TemplateApplicationAllOf';
import TemplateApplicationCreate from './model/TemplateApplicationCreate';
import TemplateApplicationStatusPatch from './model/TemplateApplicationStatusPatch';
import TemplateApplicationsPage from './model/TemplateApplicationsPage';
import TemplateApplicationsPageAllOf from './model/TemplateApplicationsPageAllOf';
import TemplateAssignment from './model/TemplateAssignment';
import TemplateAssignmentAllOf from './model/TemplateAssignmentAllOf';
import TemplateAssignmentResponse from './model/TemplateAssignmentResponse';
import TemplateAssignmentResponseAllOf from './model/TemplateAssignmentResponseAllOf';
import TemplateAssignmentStatusPatch from './model/TemplateAssignmentStatusPatch';
import TemplateAssignmentsPage from './model/TemplateAssignmentsPage';
import TemplateAssignmentsPageAllOf from './model/TemplateAssignmentsPageAllOf';
import TemplateCreate from './model/TemplateCreate';
import TemplateParameterValidator from './model/TemplateParameterValidator';
import TemplatePatch from './model/TemplatePatch';
import TemplateStatus from './model/TemplateStatus';
import TemplateStatusMeta from './model/TemplateStatusMeta';
import TemplatesPage from './model/TemplatesPage';
import TemplatesPageAllOf from './model/TemplatesPageAllOf';
import Tenant from './model/Tenant';
import TenantAllOf from './model/TenantAllOf';
import TenantCreate from './model/TenantCreate';
import TenantCreateAllOf from './model/TenantCreateAllOf';
import TenantUpdate from './model/TenantUpdate';
import TenantsPage from './model/TenantsPage';
import TenantsPageAllOf from './model/TenantsPageAllOf';
import UpdatePassword from './model/UpdatePassword';
import User from './model/User';
import UserAllOf from './model/UserAllOf';
import UserCreate from './model/UserCreate';
import UserCreateAllOf from './model/UserCreateAllOf';
import UserUpdate from './model/UserUpdate';
import UsersPage from './model/UsersPage';
import UsersPageAllOf from './model/UsersPageAllOf';
import ValidateWorkflowResponse from './model/ValidateWorkflowResponse';
import VulnerabilitiesPage from './model/VulnerabilitiesPage';
import VulnerabilitiesPageAllOf from './model/VulnerabilitiesPageAllOf';
import VulnerabilitiesRegistrationPage from './model/VulnerabilitiesRegistrationPage';
import VulnerabilitiesRegistrationPageAllOf from './model/VulnerabilitiesRegistrationPageAllOf';
import Vulnerability from './model/Vulnerability';
import VulnerabilityFeed from './model/VulnerabilityFeed';
import VulnerabilityIngestPage from './model/VulnerabilityIngestPage';
import VulnerabilityIngestPageAllOf from './model/VulnerabilityIngestPageAllOf';
import VulnerabilityIngestion from './model/VulnerabilityIngestion';
import VulnerabilityRegistration from './model/VulnerabilityRegistration';
import VulnerabilityRegistrationAllOf from './model/VulnerabilityRegistrationAllOf';
import VulnerabilityRegistrationCreate from './model/VulnerabilityRegistrationCreate';
import VulnerabilitySeverity from './model/VulnerabilitySeverity';
import VulnerabilityValidation from './model/VulnerabilityValidation';
import VulnerabilityValidationPage from './model/VulnerabilityValidationPage';
import VulnerabilityValidationPageAllOf from './model/VulnerabilityValidationPageAllOf';
import Workflow from './model/Workflow';
import WorkflowAccessMeta from './model/WorkflowAccessMeta';
import WorkflowAccessMetaType from './model/WorkflowAccessMetaType';
import WorkflowAction from './model/WorkflowAction';
import WorkflowActionBlock from './model/WorkflowActionBlock';
import WorkflowAllOf from './model/WorkflowAllOf';
import WorkflowCategory from './model/WorkflowCategory';
import WorkflowCategoryAllOf from './model/WorkflowCategoryAllOf';
import WorkflowCategoryCreate from './model/WorkflowCategoryCreate';
import WorkflowCategoryUpdate from './model/WorkflowCategoryUpdate';
import WorkflowDefAccessMeta from './model/WorkflowDefAccessMeta';
import WorkflowEvent from './model/WorkflowEvent';
import WorkflowEventAllOf from './model/WorkflowEventAllOf';
import WorkflowEventCreate from './model/WorkflowEventCreate';
import WorkflowEventUpdate from './model/WorkflowEventUpdate';
import WorkflowFooter from './model/WorkflowFooter';
import WorkflowInstance from './model/WorkflowInstance';
import WorkflowInstanceAllOf from './model/WorkflowInstanceAllOf';
import WorkflowInstanceDeleteResponse from './model/WorkflowInstanceDeleteResponse';
import WorkflowMapping from './model/WorkflowMapping';
import WorkflowMetadata from './model/WorkflowMetadata';
import WorkflowMetadataGitInfo from './model/WorkflowMetadataGitInfo';
import WorkflowSchema from './model/WorkflowSchema';
import WorkflowSchemaAllOf from './model/WorkflowSchemaAllOf';
import WorkflowSchemaByTypeResponse from './model/WorkflowSchemaByTypeResponse';
import WorkflowStartConfig from './model/WorkflowStartConfig';
import WorkflowTarget from './model/WorkflowTarget';
import WorkflowTargetAllOf from './model/WorkflowTargetAllOf';
import WorkflowTargetCreate from './model/WorkflowTargetCreate';
import WorkflowTargetUpdate from './model/WorkflowTargetUpdate';
import WorkflowVariable from './model/WorkflowVariable';
import WorkflowVariableAllOf from './model/WorkflowVariableAllOf';
import AuditingGenericEventsApi from './api/AuditingGenericEventsApi';
import BillingCyclesApi from './api/BillingCyclesApi';
import BillingEventsApi from './api/BillingEventsApi';
import BillingPricesApi from './api/BillingPricesApi';
import DeviceTemplatesApi from './api/DeviceTemplatesApi';
import DevicesApi from './api/DevicesApi';
import HealthApi from './api/HealthApi';
import IncidentChangeRequestsApi from './api/IncidentChangeRequestsApi';
import IncidentConfigurationsApi from './api/IncidentConfigurationsApi';
import IncidentsApi from './api/IncidentsApi';
import LicensingAccountsApi from './api/LicensingAccountsApi';
import LicensingConfigurationsApi from './api/LicensingConfigurationsApi';
import LicensingLicensesApi from './api/LicensingLicensesApi';
import OffersApi from './api/OffersApi';
import ProductsApi from './api/ProductsApi';
import RegistrationApi from './api/RegistrationApi';
import RolesApi from './api/RolesApi';
import SecurityApi from './api/SecurityApi';
import ServicesApi from './api/ServicesApi';
import SitesApi from './api/SitesApi';
import TemplateApplicationsApi from './api/TemplateApplicationsApi';
import TemplateAssignmentsApi from './api/TemplateAssignmentsApi';
import TemplatesApi from './api/TemplatesApi';
import TenantsApi from './api/TenantsApi';
import UsersApi from './api/UsersApi';
import ValidationApi from './api/ValidationApi';
import VulnerabilitiesApi from './api/VulnerabilitiesApi';
import WorkflowCategoriesApi from './api/WorkflowCategoriesApi';
import WorkflowEventsApi from './api/WorkflowEventsApi';
import WorkflowInstancesApi from './api/WorkflowInstancesApi';
import WorkflowSchemasApi from './api/WorkflowSchemasApi';
import WorkflowTargetsApi from './api/WorkflowTargetsApi';
import WorkflowsApi from './api/WorkflowsApi';


/**
* MSX_SDK_client_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var JavascriptMsxSdk = require('index'); // See note below*.
* var xxxSvc = new JavascriptMsxSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new JavascriptMsxSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new JavascriptMsxSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new JavascriptMsxSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.10
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccessToken model constructor.
     * @property {module:model/AccessToken}
     */
    AccessToken,

    /**
     * The BillingCostsReport model constructor.
     * @property {module:model/BillingCostsReport}
     */
    BillingCostsReport,

    /**
     * The BillingCycle model constructor.
     * @property {module:model/BillingCycle}
     */
    BillingCycle,

    /**
     * The BillingCycleAllOf model constructor.
     * @property {module:model/BillingCycleAllOf}
     */
    BillingCycleAllOf,

    /**
     * The BillingCycleCreate model constructor.
     * @property {module:model/BillingCycleCreate}
     */
    BillingCycleCreate,

    /**
     * The BillingCycleProcess model constructor.
     * @property {module:model/BillingCycleProcess}
     */
    BillingCycleProcess,

    /**
     * The BillingCycleProcessAccepted model constructor.
     * @property {module:model/BillingCycleProcessAccepted}
     */
    BillingCycleProcessAccepted,

    /**
     * The BillingCycleUpdate model constructor.
     * @property {module:model/BillingCycleUpdate}
     */
    BillingCycleUpdate,

    /**
     * The BillingCyclesPage model constructor.
     * @property {module:model/BillingCyclesPage}
     */
    BillingCyclesPage,

    /**
     * The BillingCyclesPageAllOf model constructor.
     * @property {module:model/BillingCyclesPageAllOf}
     */
    BillingCyclesPageAllOf,

    /**
     * The BillingEvent model constructor.
     * @property {module:model/BillingEvent}
     */
    BillingEvent,

    /**
     * The BillingEventAllOf model constructor.
     * @property {module:model/BillingEventAllOf}
     */
    BillingEventAllOf,

    /**
     * The BillingEventCreate model constructor.
     * @property {module:model/BillingEventCreate}
     */
    BillingEventCreate,

    /**
     * The BillingEventUpdate model constructor.
     * @property {module:model/BillingEventUpdate}
     */
    BillingEventUpdate,

    /**
     * The BillingEventsPage model constructor.
     * @property {module:model/BillingEventsPage}
     */
    BillingEventsPage,

    /**
     * The BillingEventsPageAllOf model constructor.
     * @property {module:model/BillingEventsPageAllOf}
     */
    BillingEventsPageAllOf,

    /**
     * The BillingPrice model constructor.
     * @property {module:model/BillingPrice}
     */
    BillingPrice,

    /**
     * The BillingPriceAllOf model constructor.
     * @property {module:model/BillingPriceAllOf}
     */
    BillingPriceAllOf,

    /**
     * The BillingPriceCreate model constructor.
     * @property {module:model/BillingPriceCreate}
     */
    BillingPriceCreate,

    /**
     * The BillingPriceUpdate model constructor.
     * @property {module:model/BillingPriceUpdate}
     */
    BillingPriceUpdate,

    /**
     * The BillingPricesPage model constructor.
     * @property {module:model/BillingPricesPage}
     */
    BillingPricesPage,

    /**
     * The BillingPricesPageAllOf model constructor.
     * @property {module:model/BillingPricesPageAllOf}
     */
    BillingPricesPageAllOf,

    /**
     * The CatalogAssignment model constructor.
     * @property {module:model/CatalogAssignment}
     */
    CatalogAssignment,

    /**
     * The ChangeRequest model constructor.
     * @property {module:model/ChangeRequest}
     */
    ChangeRequest,

    /**
     * The ChangeRequestAllOf model constructor.
     * @property {module:model/ChangeRequestAllOf}
     */
    ChangeRequestAllOf,

    /**
     * The ChangeRequestCreate model constructor.
     * @property {module:model/ChangeRequestCreate}
     */
    ChangeRequestCreate,

    /**
     * The ChangeRequestSummary model constructor.
     * @property {module:model/ChangeRequestSummary}
     */
    ChangeRequestSummary,

    /**
     * The ChangeRequestUpdate model constructor.
     * @property {module:model/ChangeRequestUpdate}
     */
    ChangeRequestUpdate,

    /**
     * The ChangeRequestsPage model constructor.
     * @property {module:model/ChangeRequestsPage}
     */
    ChangeRequestsPage,

    /**
     * The ChangeRequestsPageAllOf model constructor.
     * @property {module:model/ChangeRequestsPageAllOf}
     */
    ChangeRequestsPageAllOf,

    /**
     * The CostSummary model constructor.
     * @property {module:model/CostSummary}
     */
    CostSummary,

    /**
     * The Device model constructor.
     * @property {module:model/Device}
     */
    Device,

    /**
     * The DeviceAllOf model constructor.
     * @property {module:model/DeviceAllOf}
     */
    DeviceAllOf,

    /**
     * The DeviceConfigUpdate model constructor.
     * @property {module:model/DeviceConfigUpdate}
     */
    DeviceConfigUpdate,

    /**
     * The DeviceCreate model constructor.
     * @property {module:model/DeviceCreate}
     */
    DeviceCreate,

    /**
     * The DeviceCreateAllOf model constructor.
     * @property {module:model/DeviceCreateAllOf}
     */
    DeviceCreateAllOf,

    /**
     * The DevicePatch model constructor.
     * @property {module:model/DevicePatch}
     */
    DevicePatch,

    /**
     * The DeviceSummary model constructor.
     * @property {module:model/DeviceSummary}
     */
    DeviceSummary,

    /**
     * The DeviceTemplate model constructor.
     * @property {module:model/DeviceTemplate}
     */
    DeviceTemplate,

    /**
     * The DeviceTemplateAccess model constructor.
     * @property {module:model/DeviceTemplateAccess}
     */
    DeviceTemplateAccess,

    /**
     * The DeviceTemplateAccessResponse model constructor.
     * @property {module:model/DeviceTemplateAccessResponse}
     */
    DeviceTemplateAccessResponse,

    /**
     * The DeviceTemplateAttachRequest model constructor.
     * @property {module:model/DeviceTemplateAttachRequest}
     */
    DeviceTemplateAttachRequest,

    /**
     * The DeviceTemplateBatchAttachRequest model constructor.
     * @property {module:model/DeviceTemplateBatchAttachRequest}
     */
    DeviceTemplateBatchAttachRequest,

    /**
     * The DeviceTemplateCreate model constructor.
     * @property {module:model/DeviceTemplateCreate}
     */
    DeviceTemplateCreate,

    /**
     * The DeviceTemplateDetails model constructor.
     * @property {module:model/DeviceTemplateDetails}
     */
    DeviceTemplateDetails,

    /**
     * The DeviceTemplateHistory model constructor.
     * @property {module:model/DeviceTemplateHistory}
     */
    DeviceTemplateHistory,

    /**
     * The DeviceTemplateHistorySummary model constructor.
     * @property {module:model/DeviceTemplateHistorySummary}
     */
    DeviceTemplateHistorySummary,

    /**
     * The DeviceTemplateUpdateDetails model constructor.
     * @property {module:model/DeviceTemplateUpdateDetails}
     */
    DeviceTemplateUpdateDetails,

    /**
     * The DeviceTemplateUpdateRequest model constructor.
     * @property {module:model/DeviceTemplateUpdateRequest}
     */
    DeviceTemplateUpdateRequest,

    /**
     * The DeviceTemplateVersionCreate model constructor.
     * @property {module:model/DeviceTemplateVersionCreate}
     */
    DeviceTemplateVersionCreate,

    /**
     * The DeviceUpdate model constructor.
     * @property {module:model/DeviceUpdate}
     */
    DeviceUpdate,

    /**
     * The DeviceUpdateAllOf model constructor.
     * @property {module:model/DeviceUpdateAllOf}
     */
    DeviceUpdateAllOf,

    /**
     * The DevicesPage model constructor.
     * @property {module:model/DevicesPage}
     */
    DevicesPage,

    /**
     * The DevicesPageAllOf model constructor.
     * @property {module:model/DevicesPageAllOf}
     */
    DevicesPageAllOf,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The GenericEvent model constructor.
     * @property {module:model/GenericEvent}
     */
    GenericEvent,

    /**
     * The GenericEventAllOf model constructor.
     * @property {module:model/GenericEventAllOf}
     */
    GenericEventAllOf,

    /**
     * The GenericEventCreate model constructor.
     * @property {module:model/GenericEventCreate}
     */
    GenericEventCreate,

    /**
     * The GenericEventSecurity model constructor.
     * @property {module:model/GenericEventSecurity}
     */
    GenericEventSecurity,

    /**
     * The GenericEventSeverity model constructor.
     * @property {module:model/GenericEventSeverity}
     */
    GenericEventSeverity,

    /**
     * The GenericEventTrace model constructor.
     * @property {module:model/GenericEventTrace}
     */
    GenericEventTrace,

    /**
     * The Incident model constructor.
     * @property {module:model/Incident}
     */
    Incident,

    /**
     * The IncidentAllOf model constructor.
     * @property {module:model/IncidentAllOf}
     */
    IncidentAllOf,

    /**
     * The IncidentCancel model constructor.
     * @property {module:model/IncidentCancel}
     */
    IncidentCancel,

    /**
     * The IncidentConfig model constructor.
     * @property {module:model/IncidentConfig}
     */
    IncidentConfig,

    /**
     * The IncidentConfigPatch model constructor.
     * @property {module:model/IncidentConfigPatch}
     */
    IncidentConfigPatch,

    /**
     * The IncidentConfigUpdate model constructor.
     * @property {module:model/IncidentConfigUpdate}
     */
    IncidentConfigUpdate,

    /**
     * The IncidentCreate model constructor.
     * @property {module:model/IncidentCreate}
     */
    IncidentCreate,

    /**
     * The IncidentUpdate model constructor.
     * @property {module:model/IncidentUpdate}
     */
    IncidentUpdate,

    /**
     * The IncidentsPage model constructor.
     * @property {module:model/IncidentsPage}
     */
    IncidentsPage,

    /**
     * The IncidentsPageAllOf model constructor.
     * @property {module:model/IncidentsPageAllOf}
     */
    IncidentsPageAllOf,

    /**
     * The LegacyAbsoluteConfig model constructor.
     * @property {module:model/LegacyAbsoluteConfig}
     */
    LegacyAbsoluteConfig,

    /**
     * The LegacyAddress model constructor.
     * @property {module:model/LegacyAddress}
     */
    LegacyAddress,

    /**
     * The LegacyNsoResponseTypes model constructor.
     * @property {module:model/LegacyNsoResponseTypes}
     */
    LegacyNsoResponseTypes,

    /**
     * The LegacyRelativeConfig model constructor.
     * @property {module:model/LegacyRelativeConfig}
     */
    LegacyRelativeConfig,

    /**
     * The LegacyScheduleConfig model constructor.
     * @property {module:model/LegacyScheduleConfig}
     */
    LegacyScheduleConfig,

    /**
     * The LegacyServiceOrder model constructor.
     * @property {module:model/LegacyServiceOrder}
     */
    LegacyServiceOrder,

    /**
     * The LegacyServiceOrderDetail model constructor.
     * @property {module:model/LegacyServiceOrderDetail}
     */
    LegacyServiceOrderDetail,

    /**
     * The LegacyServiceOrderResponse model constructor.
     * @property {module:model/LegacyServiceOrderResponse}
     */
    LegacyServiceOrderResponse,

    /**
     * The LegacySite model constructor.
     * @property {module:model/LegacySite}
     */
    LegacySite,

    /**
     * The LegacySiteDevice model constructor.
     * @property {module:model/LegacySiteDevice}
     */
    LegacySiteDevice,

    /**
     * The LegacySiteDeviceOnboard model constructor.
     * @property {module:model/LegacySiteDeviceOnboard}
     */
    LegacySiteDeviceOnboard,

    /**
     * The LegacySubscriptionDetail model constructor.
     * @property {module:model/LegacySubscriptionDetail}
     */
    LegacySubscriptionDetail,

    /**
     * The LicenseDetails model constructor.
     * @property {module:model/LicenseDetails}
     */
    LicenseDetails,

    /**
     * The LicenseSummary model constructor.
     * @property {module:model/LicenseSummary}
     */
    LicenseSummary,

    /**
     * The ManageChangeRequestPending model constructor.
     * @property {module:model/ManageChangeRequestPending}
     */
    ManageChangeRequestPending,

    /**
     * The NSOConfigDataXPath model constructor.
     * @property {module:model/NSOConfigDataXPath}
     */
    NSOConfigDataXPath,

    /**
     * The NameValue model constructor.
     * @property {module:model/NameValue}
     */
    NameValue,

    /**
     * The Offer model constructor.
     * @property {module:model/Offer}
     */
    Offer,

    /**
     * The OfferAllOf model constructor.
     * @property {module:model/OfferAllOf}
     */
    OfferAllOf,

    /**
     * The OfferCreate model constructor.
     * @property {module:model/OfferCreate}
     */
    OfferCreate,

    /**
     * The OfferUpdate model constructor.
     * @property {module:model/OfferUpdate}
     */
    OfferUpdate,

    /**
     * The OffersPage model constructor.
     * @property {module:model/OffersPage}
     */
    OffersPage,

    /**
     * The OffersPageAllOf model constructor.
     * @property {module:model/OffersPageAllOf}
     */
    OffersPageAllOf,

    /**
     * The PageHeader model constructor.
     * @property {module:model/PageHeader}
     */
    PageHeader,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductAllOf model constructor.
     * @property {module:model/ProductAllOf}
     */
    ProductAllOf,

    /**
     * The ProductCreate model constructor.
     * @property {module:model/ProductCreate}
     */
    ProductCreate,

    /**
     * The ProductUpdate model constructor.
     * @property {module:model/ProductUpdate}
     */
    ProductUpdate,

    /**
     * The ProductsPage model constructor.
     * @property {module:model/ProductsPage}
     */
    ProductsPage,

    /**
     * The ProductsPageAllOf model constructor.
     * @property {module:model/ProductsPageAllOf}
     */
    ProductsPageAllOf,

    /**
     * The ResourceHealth model constructor.
     * @property {module:model/ResourceHealth}
     */
    ResourceHealth,

    /**
     * The ResourceStatus model constructor.
     * @property {module:model/ResourceStatus}
     */
    ResourceStatus,

    /**
     * The ResourceType model constructor.
     * @property {module:model/ResourceType}
     */
    ResourceType,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The Service model constructor.
     * @property {module:model/Service}
     */
    Service,

    /**
     * The ServiceAllOf model constructor.
     * @property {module:model/ServiceAllOf}
     */
    ServiceAllOf,

    /**
     * The ServiceElement model constructor.
     * @property {module:model/ServiceElement}
     */
    ServiceElement,

    /**
     * The ServiceElementPrice model constructor.
     * @property {module:model/ServiceElementPrice}
     */
    ServiceElementPrice,

    /**
     * The ServiceNowConfiguration model constructor.
     * @property {module:model/ServiceNowConfiguration}
     */
    ServiceNowConfiguration,

    /**
     * The ServiceNowConfigurationCreate model constructor.
     * @property {module:model/ServiceNowConfigurationCreate}
     */
    ServiceNowConfigurationCreate,

    /**
     * The ServiceNowConfigurationRequest model constructor.
     * @property {module:model/ServiceNowConfigurationRequest}
     */
    ServiceNowConfigurationRequest,

    /**
     * The ServiceNowConfigurationsPage model constructor.
     * @property {module:model/ServiceNowConfigurationsPage}
     */
    ServiceNowConfigurationsPage,

    /**
     * The ServiceNowConfigurationsPageAllOf model constructor.
     * @property {module:model/ServiceNowConfigurationsPageAllOf}
     */
    ServiceNowConfigurationsPageAllOf,

    /**
     * The ServiceSLMUIConfig model constructor.
     * @property {module:model/ServiceSLMUIConfig}
     */
    ServiceSLMUIConfig,

    /**
     * The ServiceUIConfig model constructor.
     * @property {module:model/ServiceUIConfig}
     */
    ServiceUIConfig,

    /**
     * The ServiceUILink model constructor.
     * @property {module:model/ServiceUILink}
     */
    ServiceUILink,

    /**
     * The ServiceUIResource model constructor.
     * @property {module:model/ServiceUIResource}
     */
    ServiceUIResource,

    /**
     * The ServiceUpdate model constructor.
     * @property {module:model/ServiceUpdate}
     */
    ServiceUpdate,

    /**
     * The ServicesPage model constructor.
     * @property {module:model/ServicesPage}
     */
    ServicesPage,

    /**
     * The ServicesPageAllOf model constructor.
     * @property {module:model/ServicesPageAllOf}
     */
    ServicesPageAllOf,

    /**
     * The Site model constructor.
     * @property {module:model/Site}
     */
    Site,

    /**
     * The SiteAddress model constructor.
     * @property {module:model/SiteAddress}
     */
    SiteAddress,

    /**
     * The SiteContact model constructor.
     * @property {module:model/SiteContact}
     */
    SiteContact,

    /**
     * The SiteCreate model constructor.
     * @property {module:model/SiteCreate}
     */
    SiteCreate,

    /**
     * The SiteCreateAllOf model constructor.
     * @property {module:model/SiteCreateAllOf}
     */
    SiteCreateAllOf,

    /**
     * The SiteLocation model constructor.
     * @property {module:model/SiteLocation}
     */
    SiteLocation,

    /**
     * The SiteStatus model constructor.
     * @property {module:model/SiteStatus}
     */
    SiteStatus,

    /**
     * The SiteUpdate model constructor.
     * @property {module:model/SiteUpdate}
     */
    SiteUpdate,

    /**
     * The SitesPage model constructor.
     * @property {module:model/SitesPage}
     */
    SitesPage,

    /**
     * The SitesPageAllOf model constructor.
     * @property {module:model/SitesPageAllOf}
     */
    SitesPageAllOf,

    /**
     * The SmartAccountConfiguration model constructor.
     * @property {module:model/SmartAccountConfiguration}
     */
    SmartAccountConfiguration,

    /**
     * The SmartAccountConfigurationCreate model constructor.
     * @property {module:model/SmartAccountConfigurationCreate}
     */
    SmartAccountConfigurationCreate,

    /**
     * The SmartAccountConfigurationUpdate model constructor.
     * @property {module:model/SmartAccountConfigurationUpdate}
     */
    SmartAccountConfigurationUpdate,

    /**
     * The SmartAccountType model constructor.
     * @property {module:model/SmartAccountType}
     */
    SmartAccountType,

    /**
     * The SmartAccountUser model constructor.
     * @property {module:model/SmartAccountUser}
     */
    SmartAccountUser,

    /**
     * The SmartAccountUserRole model constructor.
     * @property {module:model/SmartAccountUserRole}
     */
    SmartAccountUserRole,

    /**
     * The SmartUserAccounts model constructor.
     * @property {module:model/SmartUserAccounts}
     */
    SmartUserAccounts,

    /**
     * The SmartUserAccountsAllOf model constructor.
     * @property {module:model/SmartUserAccountsAllOf}
     */
    SmartUserAccountsAllOf,

    /**
     * The StartWorkflowResponse model constructor.
     * @property {module:model/StartWorkflowResponse}
     */
    StartWorkflowResponse,

    /**
     * The Template model constructor.
     * @property {module:model/Template}
     */
    Template,

    /**
     * The TemplateApplication model constructor.
     * @property {module:model/TemplateApplication}
     */
    TemplateApplication,

    /**
     * The TemplateApplicationAllOf model constructor.
     * @property {module:model/TemplateApplicationAllOf}
     */
    TemplateApplicationAllOf,

    /**
     * The TemplateApplicationCreate model constructor.
     * @property {module:model/TemplateApplicationCreate}
     */
    TemplateApplicationCreate,

    /**
     * The TemplateApplicationStatusPatch model constructor.
     * @property {module:model/TemplateApplicationStatusPatch}
     */
    TemplateApplicationStatusPatch,

    /**
     * The TemplateApplicationsPage model constructor.
     * @property {module:model/TemplateApplicationsPage}
     */
    TemplateApplicationsPage,

    /**
     * The TemplateApplicationsPageAllOf model constructor.
     * @property {module:model/TemplateApplicationsPageAllOf}
     */
    TemplateApplicationsPageAllOf,

    /**
     * The TemplateAssignment model constructor.
     * @property {module:model/TemplateAssignment}
     */
    TemplateAssignment,

    /**
     * The TemplateAssignmentAllOf model constructor.
     * @property {module:model/TemplateAssignmentAllOf}
     */
    TemplateAssignmentAllOf,

    /**
     * The TemplateAssignmentResponse model constructor.
     * @property {module:model/TemplateAssignmentResponse}
     */
    TemplateAssignmentResponse,

    /**
     * The TemplateAssignmentResponseAllOf model constructor.
     * @property {module:model/TemplateAssignmentResponseAllOf}
     */
    TemplateAssignmentResponseAllOf,

    /**
     * The TemplateAssignmentStatusPatch model constructor.
     * @property {module:model/TemplateAssignmentStatusPatch}
     */
    TemplateAssignmentStatusPatch,

    /**
     * The TemplateAssignmentsPage model constructor.
     * @property {module:model/TemplateAssignmentsPage}
     */
    TemplateAssignmentsPage,

    /**
     * The TemplateAssignmentsPageAllOf model constructor.
     * @property {module:model/TemplateAssignmentsPageAllOf}
     */
    TemplateAssignmentsPageAllOf,

    /**
     * The TemplateCreate model constructor.
     * @property {module:model/TemplateCreate}
     */
    TemplateCreate,

    /**
     * The TemplateParameterValidator model constructor.
     * @property {module:model/TemplateParameterValidator}
     */
    TemplateParameterValidator,

    /**
     * The TemplatePatch model constructor.
     * @property {module:model/TemplatePatch}
     */
    TemplatePatch,

    /**
     * The TemplateStatus model constructor.
     * @property {module:model/TemplateStatus}
     */
    TemplateStatus,

    /**
     * The TemplateStatusMeta model constructor.
     * @property {module:model/TemplateStatusMeta}
     */
    TemplateStatusMeta,

    /**
     * The TemplatesPage model constructor.
     * @property {module:model/TemplatesPage}
     */
    TemplatesPage,

    /**
     * The TemplatesPageAllOf model constructor.
     * @property {module:model/TemplatesPageAllOf}
     */
    TemplatesPageAllOf,

    /**
     * The Tenant model constructor.
     * @property {module:model/Tenant}
     */
    Tenant,

    /**
     * The TenantAllOf model constructor.
     * @property {module:model/TenantAllOf}
     */
    TenantAllOf,

    /**
     * The TenantCreate model constructor.
     * @property {module:model/TenantCreate}
     */
    TenantCreate,

    /**
     * The TenantCreateAllOf model constructor.
     * @property {module:model/TenantCreateAllOf}
     */
    TenantCreateAllOf,

    /**
     * The TenantUpdate model constructor.
     * @property {module:model/TenantUpdate}
     */
    TenantUpdate,

    /**
     * The TenantsPage model constructor.
     * @property {module:model/TenantsPage}
     */
    TenantsPage,

    /**
     * The TenantsPageAllOf model constructor.
     * @property {module:model/TenantsPageAllOf}
     */
    TenantsPageAllOf,

    /**
     * The UpdatePassword model constructor.
     * @property {module:model/UpdatePassword}
     */
    UpdatePassword,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserAllOf model constructor.
     * @property {module:model/UserAllOf}
     */
    UserAllOf,

    /**
     * The UserCreate model constructor.
     * @property {module:model/UserCreate}
     */
    UserCreate,

    /**
     * The UserCreateAllOf model constructor.
     * @property {module:model/UserCreateAllOf}
     */
    UserCreateAllOf,

    /**
     * The UserUpdate model constructor.
     * @property {module:model/UserUpdate}
     */
    UserUpdate,

    /**
     * The UsersPage model constructor.
     * @property {module:model/UsersPage}
     */
    UsersPage,

    /**
     * The UsersPageAllOf model constructor.
     * @property {module:model/UsersPageAllOf}
     */
    UsersPageAllOf,

    /**
     * The ValidateWorkflowResponse model constructor.
     * @property {module:model/ValidateWorkflowResponse}
     */
    ValidateWorkflowResponse,

    /**
     * The VulnerabilitiesPage model constructor.
     * @property {module:model/VulnerabilitiesPage}
     */
    VulnerabilitiesPage,

    /**
     * The VulnerabilitiesPageAllOf model constructor.
     * @property {module:model/VulnerabilitiesPageAllOf}
     */
    VulnerabilitiesPageAllOf,

    /**
     * The VulnerabilitiesRegistrationPage model constructor.
     * @property {module:model/VulnerabilitiesRegistrationPage}
     */
    VulnerabilitiesRegistrationPage,

    /**
     * The VulnerabilitiesRegistrationPageAllOf model constructor.
     * @property {module:model/VulnerabilitiesRegistrationPageAllOf}
     */
    VulnerabilitiesRegistrationPageAllOf,

    /**
     * The Vulnerability model constructor.
     * @property {module:model/Vulnerability}
     */
    Vulnerability,

    /**
     * The VulnerabilityFeed model constructor.
     * @property {module:model/VulnerabilityFeed}
     */
    VulnerabilityFeed,

    /**
     * The VulnerabilityIngestPage model constructor.
     * @property {module:model/VulnerabilityIngestPage}
     */
    VulnerabilityIngestPage,

    /**
     * The VulnerabilityIngestPageAllOf model constructor.
     * @property {module:model/VulnerabilityIngestPageAllOf}
     */
    VulnerabilityIngestPageAllOf,

    /**
     * The VulnerabilityIngestion model constructor.
     * @property {module:model/VulnerabilityIngestion}
     */
    VulnerabilityIngestion,

    /**
     * The VulnerabilityRegistration model constructor.
     * @property {module:model/VulnerabilityRegistration}
     */
    VulnerabilityRegistration,

    /**
     * The VulnerabilityRegistrationAllOf model constructor.
     * @property {module:model/VulnerabilityRegistrationAllOf}
     */
    VulnerabilityRegistrationAllOf,

    /**
     * The VulnerabilityRegistrationCreate model constructor.
     * @property {module:model/VulnerabilityRegistrationCreate}
     */
    VulnerabilityRegistrationCreate,

    /**
     * The VulnerabilitySeverity model constructor.
     * @property {module:model/VulnerabilitySeverity}
     */
    VulnerabilitySeverity,

    /**
     * The VulnerabilityValidation model constructor.
     * @property {module:model/VulnerabilityValidation}
     */
    VulnerabilityValidation,

    /**
     * The VulnerabilityValidationPage model constructor.
     * @property {module:model/VulnerabilityValidationPage}
     */
    VulnerabilityValidationPage,

    /**
     * The VulnerabilityValidationPageAllOf model constructor.
     * @property {module:model/VulnerabilityValidationPageAllOf}
     */
    VulnerabilityValidationPageAllOf,

    /**
     * The Workflow model constructor.
     * @property {module:model/Workflow}
     */
    Workflow,

    /**
     * The WorkflowAccessMeta model constructor.
     * @property {module:model/WorkflowAccessMeta}
     */
    WorkflowAccessMeta,

    /**
     * The WorkflowAccessMetaType model constructor.
     * @property {module:model/WorkflowAccessMetaType}
     */
    WorkflowAccessMetaType,

    /**
     * The WorkflowAction model constructor.
     * @property {module:model/WorkflowAction}
     */
    WorkflowAction,

    /**
     * The WorkflowActionBlock model constructor.
     * @property {module:model/WorkflowActionBlock}
     */
    WorkflowActionBlock,

    /**
     * The WorkflowAllOf model constructor.
     * @property {module:model/WorkflowAllOf}
     */
    WorkflowAllOf,

    /**
     * The WorkflowCategory model constructor.
     * @property {module:model/WorkflowCategory}
     */
    WorkflowCategory,

    /**
     * The WorkflowCategoryAllOf model constructor.
     * @property {module:model/WorkflowCategoryAllOf}
     */
    WorkflowCategoryAllOf,

    /**
     * The WorkflowCategoryCreate model constructor.
     * @property {module:model/WorkflowCategoryCreate}
     */
    WorkflowCategoryCreate,

    /**
     * The WorkflowCategoryUpdate model constructor.
     * @property {module:model/WorkflowCategoryUpdate}
     */
    WorkflowCategoryUpdate,

    /**
     * The WorkflowDefAccessMeta model constructor.
     * @property {module:model/WorkflowDefAccessMeta}
     */
    WorkflowDefAccessMeta,

    /**
     * The WorkflowEvent model constructor.
     * @property {module:model/WorkflowEvent}
     */
    WorkflowEvent,

    /**
     * The WorkflowEventAllOf model constructor.
     * @property {module:model/WorkflowEventAllOf}
     */
    WorkflowEventAllOf,

    /**
     * The WorkflowEventCreate model constructor.
     * @property {module:model/WorkflowEventCreate}
     */
    WorkflowEventCreate,

    /**
     * The WorkflowEventUpdate model constructor.
     * @property {module:model/WorkflowEventUpdate}
     */
    WorkflowEventUpdate,

    /**
     * The WorkflowFooter model constructor.
     * @property {module:model/WorkflowFooter}
     */
    WorkflowFooter,

    /**
     * The WorkflowInstance model constructor.
     * @property {module:model/WorkflowInstance}
     */
    WorkflowInstance,

    /**
     * The WorkflowInstanceAllOf model constructor.
     * @property {module:model/WorkflowInstanceAllOf}
     */
    WorkflowInstanceAllOf,

    /**
     * The WorkflowInstanceDeleteResponse model constructor.
     * @property {module:model/WorkflowInstanceDeleteResponse}
     */
    WorkflowInstanceDeleteResponse,

    /**
     * The WorkflowMapping model constructor.
     * @property {module:model/WorkflowMapping}
     */
    WorkflowMapping,

    /**
     * The WorkflowMetadata model constructor.
     * @property {module:model/WorkflowMetadata}
     */
    WorkflowMetadata,

    /**
     * The WorkflowMetadataGitInfo model constructor.
     * @property {module:model/WorkflowMetadataGitInfo}
     */
    WorkflowMetadataGitInfo,

    /**
     * The WorkflowSchema model constructor.
     * @property {module:model/WorkflowSchema}
     */
    WorkflowSchema,

    /**
     * The WorkflowSchemaAllOf model constructor.
     * @property {module:model/WorkflowSchemaAllOf}
     */
    WorkflowSchemaAllOf,

    /**
     * The WorkflowSchemaByTypeResponse model constructor.
     * @property {module:model/WorkflowSchemaByTypeResponse}
     */
    WorkflowSchemaByTypeResponse,

    /**
     * The WorkflowStartConfig model constructor.
     * @property {module:model/WorkflowStartConfig}
     */
    WorkflowStartConfig,

    /**
     * The WorkflowTarget model constructor.
     * @property {module:model/WorkflowTarget}
     */
    WorkflowTarget,

    /**
     * The WorkflowTargetAllOf model constructor.
     * @property {module:model/WorkflowTargetAllOf}
     */
    WorkflowTargetAllOf,

    /**
     * The WorkflowTargetCreate model constructor.
     * @property {module:model/WorkflowTargetCreate}
     */
    WorkflowTargetCreate,

    /**
     * The WorkflowTargetUpdate model constructor.
     * @property {module:model/WorkflowTargetUpdate}
     */
    WorkflowTargetUpdate,

    /**
     * The WorkflowVariable model constructor.
     * @property {module:model/WorkflowVariable}
     */
    WorkflowVariable,

    /**
     * The WorkflowVariableAllOf model constructor.
     * @property {module:model/WorkflowVariableAllOf}
     */
    WorkflowVariableAllOf,

    /**
    * The AuditingGenericEventsApi service constructor.
    * @property {module:api/AuditingGenericEventsApi}
    */
    AuditingGenericEventsApi,

    /**
    * The BillingCyclesApi service constructor.
    * @property {module:api/BillingCyclesApi}
    */
    BillingCyclesApi,

    /**
    * The BillingEventsApi service constructor.
    * @property {module:api/BillingEventsApi}
    */
    BillingEventsApi,

    /**
    * The BillingPricesApi service constructor.
    * @property {module:api/BillingPricesApi}
    */
    BillingPricesApi,

    /**
    * The DeviceTemplatesApi service constructor.
    * @property {module:api/DeviceTemplatesApi}
    */
    DeviceTemplatesApi,

    /**
    * The DevicesApi service constructor.
    * @property {module:api/DevicesApi}
    */
    DevicesApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The IncidentChangeRequestsApi service constructor.
    * @property {module:api/IncidentChangeRequestsApi}
    */
    IncidentChangeRequestsApi,

    /**
    * The IncidentConfigurationsApi service constructor.
    * @property {module:api/IncidentConfigurationsApi}
    */
    IncidentConfigurationsApi,

    /**
    * The IncidentsApi service constructor.
    * @property {module:api/IncidentsApi}
    */
    IncidentsApi,

    /**
    * The LicensingAccountsApi service constructor.
    * @property {module:api/LicensingAccountsApi}
    */
    LicensingAccountsApi,

    /**
    * The LicensingConfigurationsApi service constructor.
    * @property {module:api/LicensingConfigurationsApi}
    */
    LicensingConfigurationsApi,

    /**
    * The LicensingLicensesApi service constructor.
    * @property {module:api/LicensingLicensesApi}
    */
    LicensingLicensesApi,

    /**
    * The OffersApi service constructor.
    * @property {module:api/OffersApi}
    */
    OffersApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:api/ProductsApi}
    */
    ProductsApi,

    /**
    * The RegistrationApi service constructor.
    * @property {module:api/RegistrationApi}
    */
    RegistrationApi,

    /**
    * The RolesApi service constructor.
    * @property {module:api/RolesApi}
    */
    RolesApi,

    /**
    * The SecurityApi service constructor.
    * @property {module:api/SecurityApi}
    */
    SecurityApi,

    /**
    * The ServicesApi service constructor.
    * @property {module:api/ServicesApi}
    */
    ServicesApi,

    /**
    * The SitesApi service constructor.
    * @property {module:api/SitesApi}
    */
    SitesApi,

    /**
    * The TemplateApplicationsApi service constructor.
    * @property {module:api/TemplateApplicationsApi}
    */
    TemplateApplicationsApi,

    /**
    * The TemplateAssignmentsApi service constructor.
    * @property {module:api/TemplateAssignmentsApi}
    */
    TemplateAssignmentsApi,

    /**
    * The TemplatesApi service constructor.
    * @property {module:api/TemplatesApi}
    */
    TemplatesApi,

    /**
    * The TenantsApi service constructor.
    * @property {module:api/TenantsApi}
    */
    TenantsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The ValidationApi service constructor.
    * @property {module:api/ValidationApi}
    */
    ValidationApi,

    /**
    * The VulnerabilitiesApi service constructor.
    * @property {module:api/VulnerabilitiesApi}
    */
    VulnerabilitiesApi,

    /**
    * The WorkflowCategoriesApi service constructor.
    * @property {module:api/WorkflowCategoriesApi}
    */
    WorkflowCategoriesApi,

    /**
    * The WorkflowEventsApi service constructor.
    * @property {module:api/WorkflowEventsApi}
    */
    WorkflowEventsApi,

    /**
    * The WorkflowInstancesApi service constructor.
    * @property {module:api/WorkflowInstancesApi}
    */
    WorkflowInstancesApi,

    /**
    * The WorkflowSchemasApi service constructor.
    * @property {module:api/WorkflowSchemasApi}
    */
    WorkflowSchemasApi,

    /**
    * The WorkflowTargetsApi service constructor.
    * @property {module:api/WorkflowTargetsApi}
    */
    WorkflowTargetsApi,

    /**
    * The WorkflowsApi service constructor.
    * @property {module:api/WorkflowsApi}
    */
    WorkflowsApi
};
