/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JavascriptMsxSdk);
  }
}(this, function(expect, JavascriptMsxSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JavascriptMsxSdk.BillingCyclesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BillingCyclesApi', function() {
    describe('addBillingCycle', function() {
      it('should call addBillingCycle successfully', function(done) {
        //uncomment below and update the code to test addBillingCycle
        //instance.addBillingCycle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBillingCycle', function() {
      it('should call deleteBillingCycle successfully', function(done) {
        //uncomment below and update the code to test deleteBillingCycle
        //instance.deleteBillingCycle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBillingCycle', function() {
      it('should call getBillingCycle successfully', function(done) {
        //uncomment below and update the code to test getBillingCycle
        //instance.getBillingCycle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBillingCyclesPage', function() {
      it('should call getBillingCyclesPage successfully', function(done) {
        //uncomment below and update the code to test getBillingCyclesPage
        //instance.getBillingCyclesPage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('processBillingCycle', function() {
      it('should call processBillingCycle successfully', function(done) {
        //uncomment below and update the code to test processBillingCycle
        //instance.processBillingCycle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBillingCycle', function() {
      it('should call updateBillingCycle successfully', function(done) {
        //uncomment below and update the code to test updateBillingCycle
        //instance.updateBillingCycle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
