/**
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JavascriptMsxSdk);
  }
}(this, function(expect, JavascriptMsxSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JavascriptMsxSdk.TemplateAssignmentsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateAssignmentsApi', function() {
    describe('batchAssignTemplate', function() {
      it('should call batchAssignTemplate successfully', function(done) {
        //uncomment below and update the code to test batchAssignTemplate
        //instance.batchAssignTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchUnassignTemplate', function() {
      it('should call batchUnassignTemplate successfully', function(done) {
        //uncomment below and update the code to test batchUnassignTemplate
        //instance.batchUnassignTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssignment', function() {
      it('should call getAssignment successfully', function(done) {
        //uncomment below and update the code to test getAssignment
        //instance.getAssignment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssignmentHistory', function() {
      it('should call getAssignmentHistory successfully', function(done) {
        //uncomment below and update the code to test getAssignmentHistory
        //instance.getAssignmentHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemplateAssignmentsPage', function() {
      it('should call getTemplateAssignmentsPage successfully', function(done) {
        //uncomment below and update the code to test getTemplateAssignmentsPage
        //instance.getTemplateAssignmentsPage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAssignmentStatus', function() {
      it('should call updateAssignmentStatus successfully', function(done) {
        //uncomment below and update the code to test updateAssignmentStatus
        //instance.updateAssignmentStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
